### ISSUE TITLE
Prefill modes only being usable with 100% strength makes no sense?

### ISSUE THREAD

**Issue by Adrian-LA** [Acly/krita-ai-diffusion#1106]
If Strength is at 100%, you can choose from several pre-fill modes (None, Neutral, Blur, etc.) but this selection becomes greyed out when strength is <100% and the plugin switches to "Refine" mode.

To my understanding, this doesn't make much sense. At 100% strength, SD totally ignores the input image, no? So the pre-fill is irrelevant because the result is not used.

Why are the pre-fill modes greyed out when refining? For that use case they actually seem useful.

**Comment by Acly** [comment]
>  At 100% strength, SD totally ignores the input image, no?

No. You only get uniform noise if you use 0.5 grey initial image ("Neutral"). Otherwise the generated noise is influenced by the initial color, so fill makes a difference. For SDXL more than for SD1.5 (not actually sure why that is).

I think most fill modes are not suited for less than 100%, or I don't see a use case where you 100% wouldn't be better choice.
