### ISSUE TITLE
Feature Request: Allow Automatic1111 ((Re)Forge) to be used as an alternative backend to ComfyUI

### ISSUE THREAD

**Issue by ArgentVASIMR** [Acly/krita-ai-diffusion#1107]
As title says. I prefer A1111, and would like to not have multiple Stable Diffusion installations present on my PC. It's a waste of storage space.

**Comment by LeF0URBE** [comment]
it's a waste of time. 99% sure Acly won't do because here is a beter workaround :

edit your "extra_model_paths.yaml.example" of comfyUI to target your base A1111 install instead.
all models and controlnet would be found and loaded.
now comfyUI itself is still some gigabytes, but it's also almost 2x time faster on larger model like SDXL. it also takes the same VRAM than forge.

**Comment by yhslai** [comment]
You don't need to use ComfyUI's interface _at all_ to use this plugin. You don't even need to know what ComfyUI is. The plugin will install everything for you. So there isn't really a reason to "prefer" another backend to ComfyUI.

**Comment by ArgentVASIMR** [comment]
> You don't need to use ComfyUI's interface _at all_ to use this plugin. You don't even need to know what ComfyUI is. The plugin will install everything for you. So there isn't really a reason to "prefer" another backend to ComfyUI.

Does this plugin have every feature A1111 has? txt2img, img2img, upscaling, outpainting, PNG-info, wildcard prompting, etc.? Is there anything of note missing?

**Comment by Acly** [comment]
It's not a replacement or clone. It's a different tool, focused more on productivity rather than tech experimentation.

As mentioned you can use both and [share models](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-to-share-models-from-another-folder-with-krita-ai-diffusion-plugin) to avoid wasting storage space.
