### ISSUE TITLE
Resize Canvas instead of Scale on Upscale

### ISSUE THREAD

**Issue by agoulddesign** [Acly/krita-ai-diffusion#1126]
Would it be possible to have an option to resize the canvas instead of scaling all layers when upscaling? This is causing my file sizes to become quite large if I want to keep even a few process/region layers, or make a very high resolution image.

I realize this would probably break the "use prompt" option with regions.

**Comment by Acly** [comment]
I don't see how this is helpful, since those layers no longer match your image then?

To some extent if you want large image size you will have to deal with large file size. But if I have a lot of layers, I usually make a copy (save separate .kra file as a work-in-progress), then merge most layers (keep 1 per region) before continuing at higher resolution.

**Comment by agoulddesign** [comment]
Really, they stop being very useful once scaled up, and I find it only forcing me to delete potentially useful layers. I suppose a separate file is the best option; I have considered doing this on larger projects.

I guess I can just do this manually too, if I want to keep it all in one file with a manageable file size.
