### ISSUE TITLE
Newly added LoRAs are placed at the bottom of the LoRA list

### ISSUE THREAD

**Issue by mvstrawn** [Acly/krita-ai-diffusion#1139]
If you add new LoRAs to your folders and refresh the list, the new LoRAs are placed at the bottom of your dropdown list instead of sorted into the right order. Restarting Krita after adding them does not change this.

**Comment by FeepingCreature** [comment]
Unfortunately, I doubt there's a way to fix this, at least not in this plugin alone.

Because it doesn't necessarily have direct access to the server on which ComfyUI is running, Krita AI Diffusion reuses ComfyUI's internal API to query available resources. However, that API just returns a flat list of files in whichever order the operating system lists them. (For instance, on my system it's alphabetic.) The plugin can't sort by date of addition, because ComfyUI doesn't export that information.

ComfyUI would have to add date of last change to the list of LoRAs, or even better, offer a dedicated API to query that list.

**Comment by Acly** [comment]
I assumed the bug was that they weren't sorted alphabetical (as they were before).

I fixed it on monday, just forgot to push apparently.

**Comment by Acly** [comment]
Fixed in [1.24.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.24.0)
