### ISSUE TITLE
[Request] Revised sampler settings for FLUX

### ISSUE THREAD

**Issue by waynemadsen** [Acly/krita-ai-diffusion#1178]
I'm so excited that version 1.24 has GGUF support and it works great! 

In comfy, I often play with the clip flux guidance and the CFG in the ksampler separately. Can we have access to both of these values? Or could you explain how to edit custom presets to do this?

**Comment by Acly** [comment]
Currently CFG is not used and the slider does nothing.

I'm inclined to expose Flux Guidance via the existing Guidance (CFG) slider.

CFG probably not. It comes with a hefty performance and quality decrease. Since Flux dev/schnell have it baked in, it doesnt' make much sense to use it while sampling.

**Comment by waynemadsen** [comment]
So CFG isn't doing anything? What is the Flux Guidance set to? How do we adjust it right now?
