### ISSUE TITLE
Seed ignores fixed check box

### ISSUE THREAD

**Issue by ClumsyWoodsman3** [Acly/krita-ai-diffusion#1206]
LOW PRIORITY 

Fixed seed is ignored when batch generating.  Seed appears to work for this first image.  

Example: Set fixed seed for a batch of 5 

1. Image one uses seed 
2. Image 2 increments (i think) 
3. Seed increments as image 2 and so on. 

These can easily be worked around by not generating batches.

**Comment by Acly** [comment]
I'm confused, it sounds like it's a) not ignored and b) working as intended.
What did you expect to happen?

**Comment by ClumsyWoodsman3** [comment]
Sorry, maybe my understanding isn't correct.
I would think a fixed seed would not change regardless of batch size.   In comfy when i set a fixed seed and run a batch of 20, the baseline image remains the same with subtle differences. I would expect the same behavior.

**Comment by Acly** [comment]
You can get the same behavior by increasing batch size in performance settings. Not sure about subtle differences though. All images in a batch get different random noise.

Increasing the batch count is like queuing multiple times in Comfy. If you do that with the same seed, nothing happens, because it would result in 100% the same image.

**Comment by ClumsyWoodsman3** [comment]
You absolutely right. I was adding mild changes between each batch with the same seed in comfy.
