### ISSUE TITLE
Style Prompt and Negative Prompt in Style Presets not being parsed

### ISSUE THREAD

**Issue by freecoderwaifu** [Acly/krita-ai-diffusion#1231]
Prompts typed in the Style Prompt and Negative Prompt text boxes in the Style Presets section don't seem to be getting parsed. The tooltip for the image only shows the prompt from the extension's main panel, and right click Copy Prompt also only copies that one.

![image](https://github.com/user-attachments/assets/d85fbdd5-1b5d-4ec5-a5cf-2aba7a4995a3)
![image](https://github.com/user-attachments/assets/8fa90cc3-77f9-4f18-b2a2-b00cd219f883)

Tried with both the Local Managed Server and Custom Server in case it was due to a recent standalone ComfyUI update. Using version 1.25.0.

**Comment by freecoderwaifu** [comment]
Looking back at older files, it seems to be happening for a while, but I only just now noticed it. Last saved file I have that shows the negative prompt typed in Style Presets, in the preview popup, is from June 12.

![image](https://github.com/user-attachments/assets/7797394c-be62-4f3d-9a61-7919ca69072a)

Dunno if it's just because the pop up changed to simply not show those style prompts. However, it's still testable it's not working, by typing a regular prompt in Style Presets and the generated result will be a blank prompt, which usually ends up being a random image.

**Comment by Acly** [comment]
> Copy Prompt also only copies that one.

That's intentional. I think it was briefly broken and reported as bug at some point? But if Copy Prompt included the style prompt, the style prompt would be added on top of that again, and so on. Not what you want.

As for the tooltip, that's new, the full (style expanded) prompt could be displayed there. I think it isn't stored anywhere at the moment though.

**Comment by Serasul1984** [comment]
can we get it as an option ?

**Comment by freecoderwaifu** [comment]
Seems to still be an issue as of the latest update. I'm attaching workflow dumps to hopefully clarify the issue more.

Positive prompt typed in Style Presets: a cute girl with blonde hair and a pink dress holding a red apple

[workflow with positive prompt in style.json](https://github.com/user-attachments/files/17439078/workflow.with.positive.prompt.in.style.json)
![1](https://github.com/user-attachments/assets/a3bdd903-104b-4165-b712-31533dac4af0)

Positive prompt typed in the main extension panel: a cute girl with blonde hair and a pink dress holding a red apple

[workflow with positive prompt in main window.json](https://github.com/user-attachments/files/17439098/workflow.with.positive.prompt.in.main.window.json)

![2](https://github.com/user-attachments/assets/41d7fe84-b46f-4234-a96f-a1f3e0fc6273)

The workflows show only the negative prompt in Style Presets is parsing, which I think wasn't before so that is an improvement. Positive prompt is not being sent for some reason.

Fully updated ComfyUI and all custom nodes alongside the plugin.

**Comment by Acly** [comment]
If you leave the main prompt empty, the style prompt is also not merged. Maybe that's the reason? It works for me in regular case where both prompts are present.

Not using style prompt when main prompt is empty was intentional. It can be useful to use empty prompt (especially for inpainting with something like ip-adapter). But the style prompt is always appended it tends to become the image subject, ie. the Photography style will generate images of cameras, Artwork style will generate images of painting tools...

**Comment by freecoderwaifu** [comment]
Oh that makes sense for it to work like that. I was testing it that way to see if it parsed, but wasn't aware that's how it worked. Yeah I can see the positive style prompt in the dumped workflow, with a prompt in the main window. 

Another reason I thought it wasn't working is because I was trying to add Loras directly to the positive style prompt, but now seeing how they work in the dumped workflow it also makes sense, also why the add Lora to style stuff is there in the first place. 

Thank you, closing this now.
