### ISSUE TITLE
updated to v1.25.0, broke generate function

### ISSUE THREAD

**Issue by magejosh** [Acly/krita-ai-diffusion#1239]
got prompt
Failed to validate prompt for output 22:
* (prompt):
  - Required input is missing: format
* ETN_SendImageWebSocket 22:
  - Required input is missing: format
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': 'Required input is missing: format', 'extra_info': {}}

Not sure what to do with this. I updated the plugin, and now I'm seeing this when i hit generate.

**Comment by Acly** [comment]
You run external ComfyUI and updated that also I guess?

It should add the default for `format` automatically. Is there anything suspicious in client.log?

Editing `comfy_workflow.py` to include the format like [here](https://github.com/Acly/krita-ai-diffusion/blob/custom-workflow/ai_diffusion/comfy_workflow.py#L795) should also fix it.

**Comment by magejosh** [comment]
Yes, external comfyUI, updated at the same time i updated this plugin. I was on 1.23.0 before, rolled back and it works as expected. I looked at Line 795 there in that link, just unsure how i might modify that to solve the problem, since i really just don't understand the error code to begin with. I get that it is getting the api call in the wrong format, just not sure why or how to fix.

**Comment by Acly** [comment]
Replace that line in your local code with the line from the link. It basically adds the `, format="PNG"` at the end.

Still unclear why 1.23 works and 1.25 doesn't, since the change is in the nodes, not the plugin. Both plugin versions should support the additional parameter, but it seems to be working only in the older version. I can't reproduce it though, it works for me on the latest version with and without the additional format parameter.
