### ISSUE TITLE
Last used checkpoint not saving since version 1.23.0

### ISSUE THREAD

**Issue by WatermelonMango451** [Acly/krita-ai-diffusion#1245]
I recently updated from version 1.22.0, which I had been using for a long time, to a newer version. However, I'm encountering a persistent issue in every version since 1.23, including the most recent 1.25 release. Any help resolving this would be appreciated!

The problem is that the last used checkpoint isn't being saved. It keeps reverting to the one selected during the initial local ComfyUI configuration setup, which in my case is the DreamShaper model. No matter what I try, the settings keep resetting. I've also tried setting up my custom styles, but they get reset after relaunching as well. Only switching back to 1.22 seems to help.

For reference, all my models are stored in a single folder, and ComfyUI detects them by scanning the folder path that I added to the config file located inside the server folder.

**Comment by waynemadsen** [comment]
Possibly related to issue #1227 ?

**Comment by Acly** [comment]
Issue with checkpoint of the first style being reset was fixed in [1.26.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.26.0)

Not entirely sure if it helps with this issue, but I wasn't able to reproduce checkpoints not being saved in general. Maybe try a clean reinstall of the plugin if it persists?
