### ISSUE TITLE
ComfyUI Setup missing some checkpoints

### ISSUE THREAD

**Issue by ve3** [Acly/krita-ai-diffusion#1271]
From this page ( https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup )

When I follow instruction (except running download_models.py because I can't), there are many style presets that is not working. Only 2 of these ( Digital artwork (XL), and Cimatic photo (XL) ) works.

After digging more and more I found that some of checkpoints are missing.

1. **dreamshaper_8.safetensors**
2. **flat2DAnimerge_v45Sharp.safetensors**

However, the Flux style (not Flux [schnell]) still has no checkpoint with error (_The checkpoint used by this style is not installed_).  
I have no idea what checkpoint used by this style by default.

**Comment by Acly** [comment]
See https://github.com/Acly/krita-ai-diffusion/discussions/1176 for Flux models.

Dreamshaper is listed, but I think the filename changed. I added Flat2DAnimerge.

Generally most people who go with custom ComfyUI installations bringt their own checkpoints anyway, which is why the page only lists the minimal requirements. Automatically syncing the list of models from the source would be nice, but don't have time for it at the moment.

**Comment by AMDphreak** [comment]
@Acly I think the Style Presets tab should indicate that users need to activate/install the model on another tab. That is not clear at all. Complaining about "checkpoint files" as if the user is supposed to know what those are does not communicate the need to go enable a setting on another page.
