### ISSUE TITLE
Compatability errors with older versions of python 3 ie python3.8.10

### ISSUE THREAD

**Issue by ZaZaZuul** [Acly/krita-ai-diffusion#132]
I had an error loading plugin.  The main error was 'type' object not subscriptable. could not import ai_diffusion.
the error was referencing extensions.py line 13:
    _actions: dict[str, QAction] = {}

I eventually came to the conclusion this must be a python version issue even though no python version information was specified in README.md.

I was able to fix by:
  adding "from __future__ import annotations" to top of extensions.py
  additionally importing "List" from "typing"
  replacing:
      "_actions: dict[str, QAction] = {}"
  with:
      "_actions: Dict[str, QAction] = {}"

This only works with 3.7 and 3.8, though.  Version aware/compatible code could be a great improvement.  At the very least referencing ideal python versions in README.md would be helpful.

**Comment by Acly** [comment]
In a lot of cases (Windows, AppImage) the plugin runs in Krita's embedded Python 3.10, so that's where it's most tested. What is your setup? Linux via distro package manager?

In any case I agree it's a good idea to put a minimum version in the readme. The server part will use the system Python on Linux/Mac and probably has a minimum requirement as well, I'm just not sure exactly what it is.

Regarding your fix for type annotations: I kept up the support for 3.9-and-lower a while by using `from __future__ ...` in a lot of places, but realistically something is always going to slip through. Since I develop on Windows I'm bound to Krita's 3.10, and that will likely end up being the recommended minimum version.

**Comment by Acly** [comment]
I don't have a good explanation, but it's not likely Krita uses your local Python halfway, that would mess up way more things. Are you sure you didn't start Krita 5.1.x or older when you saw the error? (Now that I read issue again, we didn't mention Krita version yet...)

Generally no Python install is needed at all on Windows, so adding a version would just be confusing. I added it for Linux/Mac though since it's required for the server there.

**Comment by ZaZaZuul** [comment]
> I don't have a good explanation, but it's not likely Krita uses your local Python halfway, that would mess up way more things. Are you sure you didn't start Krita 5.1.x or older when you saw the error? (Now that I read issue again, we didn't mention Krita version yet...)

Egg on my face, I am running Krita 5.1.5.  I should have checked that first.  Regardless, I have installed recommended python version and will update to Krita 5.2.1.
