### ISSUE TITLE
MetaData Incomplete issue

### ISSUE THREAD

**Issue by La-Star-G** [Acly/krita-ai-diffusion#1320]
Hi there,
I am using the latest 1.26. The Cinematic Pholo XL and Digital Artwork Xl give me the same error. I reinstalled and downloaded the plugin. It didn't fix it. Hope someone can help me or suggest a solution. Thanks a lot. 
<img width="163" alt="Screenshot 2024-10-24 165049" src="https://github.com/user-attachments/assets/e6c49e51-2753-484a-8902-45331d128b72">

**Comment by Acly** [comment]
It is most likely because one of the model files is corrupt (has not been downloaded properly). Try to delete and re-download them.
To find the model files, open the folder where you installed the server. Model files are located in `ComfyUI > models > checkpoints`. Deleting the file will allow you to redownload them via the installer, or you can do so manually (see the list [here](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#checkpoints)).

**Comment by La-Star-G** [comment]
Thanks for the help.
