### ISSUE TITLE
Update function with local server needs a rework

### ISSUE THREAD

**Issue by ryukra** [Acly/krita-ai-diffusion#1353]
Tried updating with the new function but I think its HORRIBLY executed.

The update is copying everything over to a seperate folder, that means if you have like 100gb models (thats not a lot especially with flux now) depending on what you have for a harddrive that could take HOURS. 

If anything goes wrong, for example if you have some custom nodes installed (happened to me). You have to do everything again.

**Comment by Acly** [comment]
Regarding models:
* It usually moves models rather than copy, which is instant. I'm not sure why it's a copy for some people (somethign Python/Windows decides).
* You can put models somewhere else via [extra_model_paths.yam](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-to-share-models-from-another-folder-with-krita-ai-diffusion-plugin)
* It would probably be best if the installer setup `extra_model_paths.yaml` by default to avoid the move/sometimes-copy. Didn't do it until now because of backwards compatibility, but I will give it a shot. Might break a thing in the next update, but should be much smoother afterwards.

Custom nodes: those are not supported for managed install. That's really out of scope, it's way too easy to nuke your install with custom nodes and impossible for a script to recover. If you need custom nodes use a separate ComfyUI install.

**Comment by Acly** [comment]
[v1.28.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.28.0) update should move models into a separate folder now, outside of ComfyUI install. So future updates no longer have to move/copy them.
