### ISSUE TITLE
Get same result if using same option

### ISSUE THREAD

**Issue by oimoyu** [Acly/krita-ai-diffusion#1368]
1.27.1

I am using workflow node to generate. If I generate with same parameter, the result is consist(very fast, may use cache), but if I change one of them, then the result is new. And if I use batch option in this addon, the result is all consist same. Also I have uncheck the fix seed option of this addon in krita.

Some kind same as this #1292 

![image](https://github.com/user-attachments/assets/3d7b7ec7-9419-42a9-af68-b52a54d57322)

**Comment by nabileisa** [comment]
You need to connect  the seed output from the `Krita canvas node` to the `seed` input in your `KSampler`
![image](https://github.com/user-attachments/assets/c66fa40a-eb5a-430b-af2a-df21236384c0)
You see the problem is  unlike when you are interacting with ComfyUI directly where the seed can randomize after each generation, The seed stored in your workflow does not randomize on generation and the workflow will always execute with the same seed stored in it, and since no other parameter has change it will return the same image, to get around that you need to insert the krita plugin seed in your ksampler and let krita randomize or make the seed fixed for you.
this way you will get a new image every time as long as you set the seed to randomize in krita.
Hope this helps.

**Comment by oimoyu** [comment]
> You see the problem is unlike when you are interacting with ComfyUI directly where the seed can randomize after each generation, The seed stored in your workflow does not randomize on generation and the workflow will always execute with the same seed stored in it, and since no other parameter has changed, it will return the same image, to get around that you need to insert the krita plugin seed in your ksampler and let the krita plugin randomize or make the seed fixed for you.

did not realize this, works now, thanks for that.

**Comment by nabileisa** [comment]
Glad I could help, I ran into the same problem some time ago and took me a while to figure it out.
