### ISSUE TITLE
download_models.py requires system python to run

### ISSUE THREAD

**Issue by tampadesignr** [Acly/krita-ai-diffusion#1403]
download_models.py requires system python to run
how to run it with the embedded version of python?

**Comment by Acly** [comment]
To use the embedded python replace `python` with the path to your embedded python.

**Comment by tampadesignr** [comment]
i tired a number of ways and it didnt work
have you tried using your own script with a custom/manual/not comfy inside of krita?
im entry level coder at best, good at following directions till they dont work..lol

love your project. point people to you all the time on reddit

**Comment by Acly** [comment]
Then you put the script. You ask questions with easy answers, but I don't really understand what the actual problem is. You say "it doesn't work", but it won't tell me much. What do you want to do, what did you try, what is the output?

Generally it's `{python} {script} {arguments}`, so in your case it might be something like
```
g:/folderformodels/python/python.exe c:/user/krita/pykrita/ai_diffusion/download_models.py g:/folderformodels
```

**Comment by tampadesignr** [comment]
didn't have it like
c:/user/krita/pykrita/ai_diffusion/download_models.py
thank you
