### ISSUE TITLE
Control Layers make colors bad

### ISSUE THREAD

**Issue by declider** [Acly/krita-ai-diffusion#1467]
Using any control layers makes colors looks comepletely horrible.
For example, there is Lineart and Scribble.
<img src="https://github.com/user-attachments/assets/65e49523-93a1-482c-ba1e-a2b616f1799c" width="300">
<img src="https://github.com/user-attachments/assets/252c3507-a1b6-4990-8fb7-0fb1780f6127" width="300">

There are some examples what i get in ComfyUI, very pleasant and expected
<img src="https://github.com/user-attachments/assets/5bc6c3cf-d2c6-4873-8b40-839dc9575838" width="300">
<img src="https://github.com/user-attachments/assets/e4f1e2a4-a937-40a2-8d17-fba303d880b5" width="300">

And what i get in Krita AI, every time all colors are random, often all purple or all green. Sometimes everything dark like night.
<img src="https://github.com/user-attachments/assets/7cfe02d4-aa80-46ef-9676-66e6b99959ca" width="300">
<img src="https://github.com/user-attachments/assets/aef266ea-63ac-4ce3-8cff-06c367954a5e" width="300">

Model: Pony Diffusion V6. 
Sampler, scheduler, steps, cfg, vae, everything same in Krita and Comfy
Same bad results in Krita for scribble only/lineart only/both together, same good result im comfy for all.
Installed on local ComfyUI
All models (except checkpoints) was downloaded through script

[Comfy workflow i used.png](https://github.com/user-attachments/assets/0fcd1c6e-5677-4436-9374-5c195f146d37)

**Comment by Acly** [comment]
Your comfy workflow has the line art control images inverted
https://huggingface.co/xinsir/controlnet-union-sdxl-1.0#lineart
note they should be _white lines on black background_!

In Krita plugin they should be _black lines on white background_, that's because it's more intuitive and what artists use. The plugin inverts it automatically.

Anyway this explains why you get different images. What you call "bad colors" is "correct", just coincidence you like the other ones better. The SDXL CN don't work that well with Pony, they have not been trained for it, so this kind of stuff is not unusual.
