### ISSUE TITLE
Using the lasso tool to generate images of the flux model will be blurry

### ISSUE THREAD

**Issue by Octrain-T** [Acly/krita-ai-diffusion#1513]
![flux 局部重绘](https://github.com/user-attachments/assets/eccf5e41-5eec-409c-9f27-fc94f9dacb6a)
![xl 局部重绘](https://github.com/user-attachments/assets/5a511cf5-6cad-41db-9a56-b5708f2e90c6)
I think this might be a bug that causes the screen to be very blurry when using the flux model to partially redraw the raw image, but very clear when using the xl model，
![屏幕截图 2024-12-26 153200](https://github.com/user-attachments/assets/adc497b4-21b9-4f5f-a565-ffbe824a1053)
![屏幕截图 2024-12-26 153143](https://github.com/user-attachments/assets/a34c6f5e-2f0c-4597-a46b-a443c7dedb04)
![屏幕截图 2024-12-26 153123](https://github.com/user-attachments/assets/7048e598-26de-493e-9aa9-8ef1e1205689)

**Comment by Acly** [comment]
SDXL is computed at higher resolution because it cannot do lower resolution well. But Flux can, so it uses original resolution.

The result is that SDXL is "sharper" because it's a downscale. But it's more a side effect of the limitations of SDXL model, not a feature.

If you want sharper results, increase your canvas resolution!
