### ISSUE TITLE
Development Tips / Workflow

### ISSUE THREAD

**Issue by AvidSpline** [Acly/krita-ai-diffusion#168]
Hey all, sorry to open an issue for something so trivial but I couldn't find a direct answer in the doc.

I'm looking to explore contributing and I didn't find specific details on the development setup in the Contribution guide. Plenty of general setup, code style, etc, but what I'm looking for specifically:

What does the development cycle look like ? Are you building the release and unzipping it into the krita directory and restarting Krita for each change ? Modifying the code directly in the plugin, restarting Krita, then porting any changes over to the GH repo ? Or is there some script or method that makes this easier that I'm missing ? 

I'm mostly a server side programmer so developing in this kind of plugin environment is new for me. Apologies if this is obvious.

**Comment by Bmarquez1997** [comment]
I'm not a contributor (yet), but I have a development environment set up for the project, and might be able to answer that question:

>Are you building the release and unzipping it into the Krita directory and restarting Krita for each change ?

If you look in the [contributing guide under plugin development](https://github.com/Acly/krita-ai-diffusion/blob/main/CONTRIBUTING.md#plugin-development) there's a section on the best way to do this.  In short, you create symlinks to the ai_diffusion directory and ai_diffusion.desktop file in the Krita plugins directory that point to your workspace folders, so you can develop in the cloned repo and the changes will automatically be loaded in Krita. I believe you will have to restart Krita every time you make changes, since I think the plugin is loaded on startup.

**Comment by AvidSpline** [comment]
Somehow I completely missed that section. I knew I was missing something simple!

I agree on the reloading, that was what I observed doing changes, building a release, and manually copying. I'd done the symlinking on my own and it wouldn't load; I'm guessing the difference is I didn't symblink the .desktop file.

Thanks for the taking the time to answer a RTFM question :D

**Comment by Bmarquez1997** [comment]
No problem, glad I could help! I asked a similar question the other day around how to do out painting and the answer turned out to be super simple so I have no room to judge 😂 We all have to start somewhere, right?
