### ISSUE TITLE
[Feature Request] Auto complete on prompt textbox

### ISSUE THREAD

**Issue by huchenlei** [Acly/krita-ai-diffusion#173]
Port https://github.com/DominikDoom/a1111-sd-webui-tagcomplete here would greatly improve prompt edit experience.

**Comment by Acly** [comment]
I believe it would give you suggestions, not automatically change anything you type. That being said, I'd also make it optional, because not all models work well with these kind of tags.

It's a big extension, and I'm not personally very interested in prompt engineering features, the focus is more on steering SD via the canvas. But if you/someone wants to add support for this to the plugin I have no objections :)

One thing to clarify would be where the tags come from, is it a dictionary that is deployed, or downloaded, or queried on the fly?
