### ISSUE TITLE
[Suggestion] Enable Github CI tests

### ISSUE THREAD

**Issue by huchenlei** [Acly/krita-ai-diffusion#179]
As we have many tests now, setting up Github CI tests can help reviewers be more confident about the code without checkout the code and run tests locally.

Details see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by huchenlei** [comment]
I am not sure how current tests are setup, but it seems like Github can handle setup <10GB pretty well through the caching mechanism. See the setup I used in sd-webui-controlnet: https://github.com/Mikubill/sd-webui-controlnet/blob/main/.github/workflows/tests.yml. In terms of speed, running on CPU probably is good enough for most tests that does not involve full steps of SD inference.

**Comment by Acly** [comment]
The current minimal test server install is 5 GB with torch cpu and no checkpoint, so ~7.5 GB with checkpoint.
This would allow running some basic diffusion tests, very slowly. Depending on how many pushes and PRs there are it might eat through minute allowance pretty quickly. Many tests (control nets, SDXL, upscaling) would still not run.

SD is really annoying to test because too low resolution or samples will just produce garbage results.

Excluding all tests that run full SD, the rest is not a problem. Leaves something of a gap though.

The caching mechanism could still be useful to speed up the installer tests. They typically download from a local mock server rather than civitai/huggingface directly.
