### ISSUE TITLE
Proposal: Create an official Discord server

### ISSUE THREAD

**Issue by ghost** [Acly/krita-ai-diffusion#182]
I think this is a really cool tool, but it could benefit from the creation of an official Discord server, linked at the top of the README. This would reduce clutter in the issues page (see #163, #72, #53, etc.), and allow people to get quicker answers to their questions about this tool than if they asked through GitHub.

Thoughts?

**Comment by PhilosophicalProgrammer** [comment]
Actually the Krita discord server can be used for this I think, so nevermind.

**Comment by Acly** [comment]
I'm not sure the Krita discord is a good fit, as large parts of Krita community are still hostile towards generative AI.

A discord around this plugin could be nice for people to help each other out with setup and installation issues, and maybe also share workflows. I'm just hesitant because I know it will be yet another thing that distracts me from doing any actual work :D

**Comment by Acly** [comment]
Also there is some advantage to collecting these kinds of issues and resolutions in one place, they are harder to search for and find when buried somewhere in discord.

**Comment by PhilosophicalProgrammer** [comment]
In that case I'll reopen the issue for further discussion.

**Comment by papersplease** [comment]
Chats are terrible for software development. They might be better for community building if you want a community _for users_. Sharing tips, tricks, results, simply shitposting, all that stuff. Otherwise it's a huge distraction.

**Comment by PhilosophicalProgrammer** [comment]
"They might be better for community building if you want a community for users. Sharing tips, tricks, results, simply shitposting, all that stuff." Yes, this is exactly why a Discord would be a good idea. People could share tips there instead of filling the repo with questions, and possibly get answers faster since they'd be talking to other users that potentially have had the same issues.

Another benefit would be that people would be able to optimize their use of this tool by sharing tips and tricks like you said and share their workflows. I don't see any downsides to it.

**Comment by PhilosophicalProgrammer** [comment]
One possible solution to not having all answers to common questions in one place would be to create an official FAQ specifically dedicated to that. Having a Discord and an FAQ is a pretty common practice for complicated pieces of software.

**Comment by SushiByte-beep** [comment]
I am not sure of discord would be the best solution but i really miss some sort of easy to approach community to discuss tips and workflows. 

I am getting completely different results with this plugin then on automatic with the same model, seed, sampler, tips and tricks you find in general don't always seem to apply here. It would love to contribute by testing and sharing what does and does not work.

**Comment by Acly** [comment]
Could use the GitHub discussions, it's similar. Lemmy has a bit higher bar of entry.
I'm not sure how discoverable it is, but it seems to work well for other projects I saw.

I also wanted to find some time to migrate some existing issues there, but time sucessfully eludes me...

**Comment by Acly** [comment]
https://github.com/Acly/krita-ai-diffusion/discussions

Still migrating some things, and finding places to link and forward to.
