### ISSUE TITLE
[Feature Request] Scale preview image in live mode

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#203]
The issue happens on high DPI displays, if the resolution of the monitor (and Krita and its windows) is high, preview in live mode becomes.... fairly small :) Would be great to have automatic scaling down to the container borders so user will scale as needed the preview in live mode

**Comment by Acly** [comment]
It does scale with the container, only I suspect the container size is in DPI-aware coordinates, and the image is actual pixels, so it's missing a multiplication somewhere...

**Comment by Acly** [comment]
@Pirog17000 Which OS are you using? It works fine for me using different display scaling on Windows. But it's possible eg. Mac retina stuff is handled differently

**Comment by Pirog17000** [comment]
@Acly Windows10

Here's demo of what happens:  https://imgur.com/a/VFvihDV
basic steps to reproduce:
- select region
- hit 'play/live' button
- try to scale the window with preview
- draw something on canvas in the region
- observe how the preview scales towards the updated size of the window

Problem is that the priview positioned and scaled weirdly by-default AND doesn't scale along with the window size

**Comment by Acly** [comment]
Okay I think I get it. But it has nothing to do with high DPI?

There are two things here to consider:
* If you select a region, and that region is smaller than the native resolution (512 for SD1.5, 1024 for SDXL), generation happens at the minimum resolution anyway but only the masked part is changed. This is reflected by the preview. If you have eg. a 2048 canvas and select a 1024 region you'd get minimal padding. I thought it would be somewhat intuitive since the position of the image in the preview reflects the position of your selection in the canvas. But maybe not. I could also crop away the padding.
* Resizing the dock window does not immediately update the image size, but it will update with the next frame. This can also be fixed, but seemed good enough for now, given how live mode is used.
