### ISSUE TITLE
A lot of the requirements for this force pickle files

### ISSUE THREAD

**Issue by MackNcD** [Acly/krita-ai-diffusion#204]
I'd recommend allowing the safetensor versions for all these files, or not shutting down the whole process if they don't have something needed for the pipeline, and allow one that doesn't require any of these potentially-dangerous-in-the-future files.

**Comment by Acly** [comment]
Which requirements are you referring to in particular? The [list here](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md) is all .safetensors, except for one upscale model, which you can actually replace with whatever upscale model you want (it just requires one to be present).

The installer still uses the .bin version in some cases, mainly because .safetensors wasn't available at the time and changing would make existing installs redownload the model.
