### ISSUE TITLE
Financial support

### ISSUE THREAD

**Issue by Jarco** [Acly/krita-ai-diffusion#205]
Hello,

I am not well-versed in Stable Diffusion development, but I still love your project and don't want it to go away. I notice that you are progressing at a fast pace and putting in a lot of effort on this project.

Although I can't contribute a substantial amount, I was exploring options to send a small donation to support the project, similar to Github Sponsors or Patreon. Is this something you are considering?

**Comment by Acly** [comment]
Hi,

I appreciate the sentiment. I haven't set up sponsorship so far. I'm devoting a lot of time to the project because I enjoy it, and it allows me to be productive while exploring a new technology. This isn't sustainable in the long run, but money isn't going to be the first issue, and I don't want to give the impression that voluntary donations are going to have much of an impact in that regard.

Which is not to say that I won't do my best to keep the project alive, or that donations can't be a genuine source of motivation. I'll keep it in mind.
