### ISSUE TITLE
Consistent image generation

### ISSUE THREAD

**Issue by IamTirion** [Acly/krita-ai-diffusion#209]
Hi, I'm looking to create illustrations for a story using Krita AI Diffusion, but every new image is very different from the previous one. I also came across a research paper that looks relevant to my problem: https://storygpt-v.s3.amazonaws.com/index.html

Is it possible to implement that paper?

If not, what is currently the best way to produce sequential images, i.e. images that look like they are from the same scene?

**Comment by IamTirion** [comment]
I see, thank you. I'll go make my suggestion to ComfyUI.

As for training a LoRA for every scene, that's not really viable, because there can easily be hundreds or thousands of scenes in one story, if not more. Besides, there can be multiple characters in one scene. Well, I guess currently this cannot be done easily.

**Comment by Acly** [comment]
It's an unsolved problem. LoRA are the most consistent, but they don't scale. The paper you link also looks like it needs to be pre-trained on your data?

Right now, you can create reference images for you scenes and characters and use them as input for the Image control layer in the plugin (that uses IP-Adapter). You have to swap around and inpaint characters individually, and it only gets you so far (struggles with details). But I think it works if you're prepared to invest some time. It can also be combined with LoRA for your main characters.

Also, the more you can sketch/draw, the easier it becomes to get what you want.

**Comment by papersplease** [comment]
> As for training a LoRA for every scene, that's not really viable, because there can easily be hundreds or thousands of scenes in one story, if not more. Besides, there can be multiple characters in one scene.

You don't do it for every scene, you do it for your style/environments in general, and possibly for characters. Combine and mix those styles. But yeah, what you want is not easy right now, and the scalability is questionable.

Yes, there are zero-shot methods as well, such as IPAdapter. They're less advanced than LoRAs. For example IPAdapter always takes a 224x224px picture by design (that's the resolution of the underlying vision model), everything else is scaled/square-cropped. Yet somehow it manages to capture your reference pretty well, even with that resolution.

Another problem with zero-shot methods is unwanted feature contamination - they extract all features from the reference, even unwanted ones (e.g. background), there's currently no way to filter those out except for training your own IPAdapter (which scales even worse).
