### ISSUE TITLE
Progress bar for generation while in live mode

### ISSUE THREAD

**Issue by larsgus** [Acly/krita-ai-diffusion#218]
There is no progress bar for generation while in live mode, so I find myself going back to generate from live to check on the progress. Is there any reason the progress mode has been removed from live mode?

**Comment by Acly** [comment]
The main use case is to get updates more or less immediately (in less than a second). That makes the progress bar not very useful and somewhat distracting. There are also very few steps, so progress bar will not have much granularity.

Some kind of "it's doing work" indicator would still be useful though, especially when it takes longer at the start due to loading models.
