### ISSUE TITLE
[Enhancement | Feature request] PowerPaint pipeline integration

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#221]
https://github.com/open-mmlab/mmagic/tree/main/projects/powerpaint
One link worth thousands words.
Better inpainting, better outpainting, stability of the image, consistency of the image

https://powerpaint.github.io/

**Comment by Pirog17000** [comment]
well, there's no CN for inpaint for SDXL models at the moment.
Possibly, a solution: https://github.com/showlab/X-Adapter 
but would be great to have it as an option during the setup of the plugin modules, as an extra option, or one of the options for outpaint/inpaint

**Comment by zengyh1900** [comment]
There are multiple options for inpainting in PowerPaint, such as text-guided object inpainting(requires text input and inserting objects into images) and text-free object removal (no need for text input). 
That means if we want to remove something we should use the option for object removal (for sure, it is not always perfect)

I tested on the online demo and got some results without cherry-picking.

with this input,  
![289913904-fa654a8b-b18c-4f2e-97c0-3eea97f850e1](https://github.com/Acly/krita-ai-diffusion/assets/7473216/f0f75146-0f3f-4562-8603-03566ef1d0c0)

I have:
![image (1)](https://github.com/Acly/krita-ai-diffusion/assets/7473216/1d73a7cc-73d5-44bf-9f48-a6d1245cf88d)

Then, I extend it in the horizontal direction,
![image (5)](https://github.com/Acly/krita-ai-diffusion/assets/7473216/21693026-47dc-4599-a22e-b18d9e02ec70)

Or in the vertical expansion ration, 
![image (4)](https://github.com/Acly/krita-ai-diffusion/assets/7473216/e509e36c-21eb-487a-ae2f-1c08f662e30d)


We are still tuning a stonger and more stable version.

**Comment by zengyh1900** [comment]
Is the inpainting model for SDXL important? We did plan to develop an inpainting model for SDXL. However, we pend it for a while due to some other reasons.

**Comment by Pirog17000** [comment]
I personally prefer more SDXL over 1.5 models - more understanding of the prompts, higher resolution, less repetition when canvas goes out of focus window (for 1.5 it was about 768x768px, sdxl supports up to 1680x1680 sometimes), so if possible - yes, that will be fantastic @zengyh1900

**Comment by Acly** [comment]
Thanks for your input, it certainly looks better than my inital try. I tried multiple modes, with and without prompt. The results I compare against were all done without any prompt or user input (only image + mask).

The paper mentions "Context-aware Inpainting" and "Object Removal" as separate mode, but I cannot find "Context-aware" in the online demo?

> Is the inpainting model for SDXL important?

ControlNet Inpaint has the advantage that you can use a specialized SD model which fits the image content for the task. General inpaint solutions on the other hand may be good for eg. photos, but not as strong in other areas. So if your use case is to inpaint photos, I don't think SDXL has a big advantage - its improvements are mainly relevant for whole image generation, and it seems less adaptable to other tasks then SD1.5.

However another use case is generating artwork that follows a certain style, and then using inpainting steps to edit and refine the image. Here it really helps if the model used for inpainting matches the one to generate the inital image. So if certain SDXL checkpoint was used, to use it also for inpaint/outpaint in order to easily match the chosen style. This is an area where SD offers much more flexibility than eg. Adobe solution.

That being said, I'm open to investigate alternatives. One idea is to use a model trained for inpaint (such as LaMA or PowerPaint) to generate initial content in the masked area, and then use any non-inpaint SD(XL) model as a second low-denoise img2img pass.

**Comment by Pirog17000** [comment]
> use a model trained for inpaint (such as LaMA or PowerPaint) to generate initial content in the masked area, and then use any non-inpaint SD(XL) model as a second low-denoise img2img pass.

this is my main approach. But at the moment I generally just paint key colors and tones for proper inpaint. 
sometimes it's very tedious, but will works. If there's a ready-to-go solution like the model specifically made for such purposes - that will be great to have it onboard

**Comment by Pirog17000** [comment]
@Acly there's one more approach has arrived:

https://github.com/damo-vilab/AnyDoor

**Comment by zhuang2002** [comment]
PowerPaint Update

We've released an updated model with enhanced stability, now available for interactive testing on our online demo.

Paper: https://arxiv.org/abs/2312.03594
HomePage: https://powerpaint.github.io/
Online Demo: https://openxlab.org.cn/apps/detail/rangoliu/PowerPaint
Code: https://github.com/open-mmlab/mmagic/tree/main/projects/powerpaint

**Comment by Pirog17000** [comment]
@Acly Inpaint controlNet model for SDXL has arrived: https://civitai.com/models/136070?modelVersionId=271562, can this be included please?

**Comment by Acly** [comment]
It's... interesting. Actually does a pretty good job at putting content into the masked area, but drastically changes the color of the entire image. So the inpaint result no longer fits into the original image.

The examples on the model page show this, and the description says

> Depending on the prompts, the rest of the image might be kept as is or modified more or less.

... but I have no idea how to "keep it as is". Anyway it's an alpha development version, not sure how you found this, but it doesn't look like it's officially released.

**Comment by Acly** [comment]
Inpaint for SDXL is implemented now in [v1.14.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.14.0) - there are also many other improvements. It's a solution that works with existing and custom SD checkpoints, which ends up being more flexible and introduces fewer additional models for this project.
