### ISSUE TITLE
Failed to download from civitai !!

### ISSUE THREAD

**Issue by buihthai25** [Acly/krita-ai-diffusion#222]
![Screenshot_1](https://github.com/Acly/krita-ai-diffusion/assets/151908823/8ccf5ac9-2c1d-4aee-ae45-468fef5916a2)

**Comment by buihthai25** [comment]
how can I fix this ?

**Comment by Acly** [comment]
Since the rest of the downloads seemed to work it might be an issue with civitai servers. You can try to download it manually in your browser.
URL is https://civitai.com/api/download/models/130072?type=Model&format=SafeTensor&size=pruned&fp=fp16 
Put it in your server path > ComfyUI > models > checkpoints
