### ISSUE TITLE
SDXL Turbo took 3 minutes to generate an image.

### ISSUE THREAD

**Issue by TruthSearcher** [Acly/krita-ai-diffusion#234]
SDXL Turbo took 3 minutes to generate an image. I was using [krita](https://github.com/Acly/krita-ai-diffusion) with a comfyui backend on a rtx 2070 and I was using about 5.3 gb of vram in the generation, why was sdxl turbo so slow?

**Comment by Pirog17000** [comment]
what was the resolution of the image and number of samples? 
do you still experience the same behavior?
do you have anything on the background occupied VRAM on top of krita plugin?

It seems that this is a lack of memory issue and tossing parts of memory between VRAM and RAM is .. slow usually
@TruthSearcher

**Comment by TruthSearcher** [comment]
for 1024x1024 it takes about 1 minute and 45 seconds. I don't have anything running on the background besides google chrome.
![image](https://github.com/Acly/krita-ai-diffusion/assets/134135767/e4162a3a-6a69-4f8e-aaf4-86e566cb8495)

**Comment by Danamir** [comment]
SDXL turbo needs only a few steps ; try setting it to 2 to 6, and lower the CFG scale around 1.0 to 2.0 .

**Comment by TruthSearcher** [comment]
I'm still having slow speeds, CPU is taking over 7 minutes. I thought SDXL turbo was supposed to be quick.

**Comment by Danamir** [comment]
You should try to see what performance you can get on a simple ComfyUI workflow before adding another step like using krita-ai-diffusion. You will get a better sense of what performance is attainable. 

The plugin will have worse performance because it forces the dimensions to be good for any other SDXL model (ie. around 1024x1024), where Turbo SDXL is especially trained at 512x512, hence the performance you see other people getting.

**Comment by Acly** [comment]
In [1.12.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0) you can now also manually set the internal resolution to 512x512 for Turbo. Now generates ~8 images per second for me...
