### ISSUE TITLE
Working on a larger canvas (not understanding a feature/not finding it?)

### ISSUE THREAD

**Issue by asakleiman** [Acly/krita-ai-diffusion#240]
Does AI Diffusion rescale its inputs and outputs to an appropriate size for comfyUI? I thought I read that it did, but when I try and generate something from a layer it sends the full resolution canvas over to comfy, which understandably chokes and hangs trying to get through it.

The last Krita AI plugin I used downscaled the canvas (or selection) to the appropriate size, then upscaled it when bringing it back to Krita - does AI Diffusion not do this? Is there any way I can enable this?

**Comment by Acly** [comment]
The size of the input/output is always the size of your canvas (or your selection, if any). There is an issue where Stable Diffusion will produce image artifacts when used outside a certain range, and this is taken care of automatically by upscaling/downscaling.

However there is no such thing as an "appropriate size for comfyUI" - technically it can generate images of any size, and in many situations that's what you want to do. There is a soft cap which depends on your hardware, available GPU memory in particular. But this depends on a lot of factors and isn't very predictable. So if you say it chokes (takes too long or runs out of memory?) you might have to choose a lower resolution for your GPU - but on other hardware it would work just fine.

There is a potential improvement to use tiling to allow GPUs with unsuifficient VRAM to work on larger resolutions too, but the process would still take a lot of time.

**Comment by asakleiman** [comment]
Yeah, I'm aware that the cap isn't intrinsic to Stable Diffusion; but I only have a 3080 and I have no idea what kind of scifi level hardware I'd need to run my usual 10k by 6k working canvases through SD in less than a week.
I also suspect something is broken in my install because while I can work with full size images, and I can do live inpainting, sending a selection to Comfy makes it choke; after the progress reaches 100% the GPU's usage and memory spike to 100% and stay there until I shut it down.

That said, is the only workflow for large canvases in AI diffusion 'export canvas to new document->rescale canvas->send to Comfy->copy results to original document->upscale'?

**Comment by Acly** [comment]
Or work with a smaller canvas. I think 10k by 6k is just not realistic if you want to incorporate AI content at the moment. I don't really understand how generating at lower resolutions would be different than choosing a lower resolution canvas in the first place - a simple upscale will not magically make the results look high-res. You might have more pixels, but it's still just as blurry and won't look good compared to actual 10k x 6k content.

If you need a high resolution in the end (like for print) it's a lot more efficient to start with a low-res canvas and only do (AI) upscale at the very end, instead of individually for every intermediate generation.

**Comment by asakleiman** [comment]
I'm using SD on my illustration work; the canvas size is the canvas size it needs to be. I'm also aware of how things look when they're scaled up.
I've been trying to integrate SD into my workflow for a while now; it could be super useful and amazing as a tool for me, but each Krita integration has some kind of weird twist or limitation and I get a 'no why would u want to do that lol' response, like now.
What I really, really want to do is to have a way to quickly fill in backgrounds of sketches and work-in-progress illustrations. Having to spend the time exporting, rescaling, reimporting, etc, really kind of eliminates the 'quick' part.
Someday someone's gonna make a Krita to Comfy integration that's just a 'krita in' and 'krita out' set of nodes and I'm gonna be super happy.

**Comment by Acly** [comment]
No that's not what I meant. I want to figure out the what the problem is, the why and what for, to get a feeling what kind of solution could work. Maybe I need to put more question marks.

From my perspective: if a user has a WxH canvas and requests to generate an image, they'd expect a WxH image to come out. I don't see a weird twist there. You initially just said that for some unspecified canvas resolution you'd want generation to run at some unspecified lower resolution and some kind of automatic scaling to fit it together.

I'm not saying this is unreasonable, but there are many unknowns there, and it's unclear how it can fit in. To build a tool that is useful for a lot of people with different requirements and expectations, you kinda need to start with the problem, and consider alternatives and compromises. Only way to skip the process is to implement it yourself.

If I got it right this seems related to #223, except the reverse. Perhaps a difference is also that in your case it sounds like you don't need to tweak this per generation, but a scaling factor could be set up once and apply throughout working on an image.

**Comment by Acly** [comment]
See [release 1.12.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.12.0) for auto-upscale options.

Note that I still can't generate 10k x 6k because ComfyUI apparently has a maximum value of 8196 for image resolutions (and I can't easily get around that for now). But 8000x4800 works fine.

**Comment by asakleiman** [comment]
Cool! I can't wait to check it out.
