### ISSUE TITLE
SDXL Openpose problem

### ISSUE THREAD

**Issue by IamTirion** [Acly/krita-ai-diffusion#253]
Hello, maybe upon seeing the title of this read, you may immediately think that Controlnet models don't work well for SDXL, everybody knows that already. Well, indeed currently, the Pose model in this plugin is terrible for me. In fact, it doesn't follow the input pose at all. Well, I came across this thread: https://github.com/Mikubill/sd-webui-controlnet/discussions/2153
which is using the same Openpose model as this Krita plugin, thiebaud_xl_openpose.

The OP also found it unusable in his own Stable Diffusion app, but when he tried it in Automatic1111, it was obvious the results were following the input pose, so he suspects there is a bug in the API. Well, the OP still hasn't fixed it in his app. However, I just want to bring this to your attention. It isn't that Openpose doesn't work well in SDXL. It actually does.

I also found another page here that is showing the same Openpose model in ComfyUI: https://mybyways.com/blog/sdxl-1-0-with-sdxl-controlnet-openpose-v2
It also works, but he is using the 5Gb model instead of the Lora that is used in this plugin.

**Comment by Acly** [comment]
I do have the impression that ControlNet does not work as well for SDXL as it does for SD1.5. I've seen other people make this observation, regardless of which tool. That being said, `thibaud_xl_openpose_256lora` which is installed by the plugin by default does work for me. Not always great, but it definitely has a noticeable effect.

I don't really see how the link you mentioned is related, it's very A1111-specific. If you suspect that the plugin does not apply ControlNet correctly you can try to fix the seed and input and compare against using ComfyUI directly. Please post results. Without clearly defined input and expected output it's hard to discuss potential issues.

If you want to try the full model instead of the Lora you can: remove the Lora version and download [thibaud_xl_openpose.safetensors](https://huggingface.co/lllyasviel/sd_control_collection/blob/main/thibaud_xl_openpose.safetensors) instead. The Krita plugin will accept either.

**Comment by IamTirion** [comment]
> I do have the impression that ControlNet does not work as well for SDXL as it does for SD1.5. I've seen other people make this observation, regardless of which tool. That being said, `thibaud_xl_openpose_256lora` which is installed by the plugin by default does work for me. Not always great, but it definitely has a noticeable effect.
> 
> I don't really see how the link you mentioned is related, it's very A1111-specific. If you suspect that the plugin does not apply ControlNet correctly you can try to fix the seed and input and compare against using ComfyUI directly. Please post results. Without clearly defined input and expected output it's hard to discuss potential issues.
> 
> If you want to try the full model instead of the Lora you can: remove the Lora version and download [thibaud_xl_openpose.safetensors](https://huggingface.co/lllyasviel/sd_control_collection/blob/main/thibaud_xl_openpose.safetensors) instead. The Krita plugin will accept either.

Ok thank you. Sorry, I made the assumption that it doesn't work for everybody. I will post my results in a moment.

**Comment by Acly** [comment]
Those images all look weird, regardless of pose control-net. Do you get "normal" results without the CN? Something is wrong, but not sure if it's related to the pose CN.

I'm not so surprised about the images using 90% strength: initial all white latents leave very little room for sampling to do anything. This also matches what ComfyUI produces with simple workflow. Don't know if other apps do something different.

Here is what I get with the default pose, Cinemtatic Photo (XL), 1024x1024, 100% strength, no prompt, seed 1234:
![pose-xl](https://github.com/Acly/krita-ai-diffusion/assets/6485914/8012469c-265a-4a43-ab55-35c3c4cece39)

It doesn't follow very precisely, but without pose it would just generate random images of cameras (because of the style prompt), at the very least the CN puts a person in the right spot.

**Comment by IamTirion** [comment]
Thank you. You pointed me in the right direction. For some reason when I switched the Style Presets, it didn't change the sampler, or maybe I changed it accidentally. Now I'm getting results similar to yours.
