### ISSUE TITLE
CFG rescale option under Styles

### ISSUE THREAD

**Issue by Muskelmagier** [Acly/krita-ai-diffusion#259]
Hi i would like to recommend a CFG rescaling feature because of how flawed the normal generation is in creating darker pics.

My idea would be to place this option into the styles tab simply under "quality preset".

THis here is an implementation for A1111
https://github.com/Seshelle/CFG_Rescale_webui

For ComfiUI there is this node
https://github.com/comfyanonymous/ComfyUI_experiments

It's based on this paper.
https://arxiv.org/pdf/2305.08891.pdf

This also increases the details in normal generations

**Comment by Acly** [comment]
I don't quite understand how it relates to "quality preset".
The latest release has an option to use zero terminal SNR models with a default rescale CFG of 0.7
But it's still unclear to me what an actual good parametrization is, also to generally rescale CFG (or do something more involved with [SD Dynamic Thresholding](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding)).

With "good" parametrization I mean something that is entirely automatic or otherwise intuitive with regards to what effect it has on the image, and without breaking in many situations.

See also #211
