### ISSUE TITLE
how do i remove text from image

### ISSUE THREAD

**Issue by reitenth** [Acly/krita-ai-diffusion#274]
im trying to remove text from posters to get textless posters and use inpaiting to make it match. even with the prompt empty it adds stuff instead of removing. thanks.
![image](https://github.com/Acly/krita-ai-diffusion/assets/94771708/1644b982-d1ac-487c-871a-f9ab867ba049)

**Comment by b4zz4** [comment]
add in negative prompt: "text, caption"

**Comment by reitenth** [comment]
@Acly any instructions to inpaint?

**Comment by Acly** [comment]
Going to be tough in this case if you want to just remove the text and keep existing background. I think mostly because there is little to no background information, it kind of fades to white and has a frame at the bottom behind the text.

Inpaint replaces existing content with something new that (hopefully) fits in. Text removal is a more specific task. I don't think you can get it to do that automatically. Maybe a solution like #175 would work better, or there might be more specialized technique for this...

**Comment by b4zz4** [comment]
Prompt negative with some help from a reference drawing like canny Edge:

https://github.com/Acly/krita-ai-diffusion/assets/643833/c0951c82-eaa4-4e7b-82cd-d748267f190e
