### ISSUE TITLE
[re]Error: Could not find IPAdapter model ip-adapter_sd15.safetensors, ip-adapter_sdxl_vit-h.safetensors. Make sure to download the model and place it in the ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/models folder.

### ISSUE THREAD

**Issue by kjustudy** [Acly/krita-ai-diffusion#285]
https://github.com/Acly/krita-ai-diffusion/issues/195

I am aware that this issue has been resolved at the link above. However, according to #195,

---------------
put in ComfyUI\models\ipadapter it worked:)
----------------

It is stated that this can be a solution.

But,
put in ComfyUI\models\ipadapter it worked:)
did not work when I tried it.

![StrokesPlus_gWNR1WTjQX](https://github.com/Acly/krita-ai-diffusion/assets/106743505/8ca14971-5fea-4c6c-9a0a-84aa5749a6ba)

How can I resolve this?

*Note: It was working fine originally, but suddenly one day, this error occurred.

**Comment by kjustudy** [comment]
And I have also already tried putting files in the custom node folder.

**Comment by Acly** [comment]
Maybe Stability Matrix stores the models somewhere else?

**Comment by kjustudy** [comment]
Thank you for your response

Upon examining the model files of the Stability matrix, there were no overlapping files.
![StrokesPlus_UOg0roLWvt](https://github.com/Acly/krita-ai-diffusion/assets/106743505/c9570fde-716f-4c0b-9a8c-8df9504fda34)

**Comment by Targren** [comment]
If you're using the latest StabilityMatrix it looks like the symlinks might be wonky. 

I had to put them into StabilityMatrixData/Models/InvokeIpAdapters15/ip_adapter_sd15

**Comment by kjustudy** [comment]
> If you're using the latest StabilityMatrix it looks like the symlinks/configs might be wonky.
> 
> I had to put them into StabilityMatrixData/Models/InvokeIpAdapters15/ip_adapter_sd15


I'm very grateful. Thanks to the content of this comment, it was resolved.

Users of the stability matrix should not put the model files in the model folder of the comfyui installation directory.

Instead, it worked well when I put them in the stability matrix => data 


![StrokesPlus_zGa1rQGjIC](https://github.com/Acly/krita-ai-diffusion/assets/106743505/c2f15288-a750-417f-81c8-a331d72b6644)
=> models => ipdapter folder.

**Comment by Grant-CP** [comment]
I wanted to chime in that I was having this issue with a remote computer running comfyui and I solved it. Local computer is windows 10 running Krita, comfyui api is tunneled through VS Code from a compute in Azure ML Studio. The issue as it turned out was related the the "custom paths" config. I had a previous A1111 install, and so I added a line for "ipadapter" in my custom models. For some reason, I saw in this extension's "client.log" that it was ONLY seeing the models from my A1111 folder, and not looking the the ipadapter folder for comfyui at all. See the below image for the line, which when commented out fixed the issue:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/a49d51d7-62cd-4fa7-ab02-4af21d2ab348)

I will note that I have the ip-adapters stored in two places now. One is the .bin version from the initial release, and the others were downloaded via the comfyui plugin manager.

I wonder if there is not an issue with the ipadapter_plus extension itself which causes it to not look in all of the correct directories.

Here's my log file in case you are curious. I've seen multiple other users submit issues related to this issue:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/ffd08a15-49c2-47df-9a1e-b17993f3aab6)

I also expect the issue would have been resolved if I renamed my ip-adapter_XL.bin model to something else, or if I edited the code in client.py to match the name of my model. I opted to use the recommended safetensors model instead.
