### ISSUE TITLE
Error with SDXL model in LIVE mode

### ISSUE THREAD

**Issue by freemde23** [Acly/krita-ai-diffusion#293]
When using the SDXL model, it shows that workload has not been installed.
But it can be used in Generate.
However, the LCM SDXL model that is normally used in ComfyUI keeps showing the following in Live: LCM lora model not found for SDXL, and the LCM lora model that already has SDXL cannot be recognized.
![2024-01-02_233156](https://github.com/Acly/krita-ai-diffusion/assets/122530501/28bdfcc8-4679-446d-ac70-3a39f5497455)

**Comment by Acly** [comment]
Generate does not use LCM by default, so that's why it works. 

Both errors (the workload one, and the live LCM LoRA) have the same cause: the LCM LoRA for SDXL is not found.
* The LCM LoRA must follow the naming convention described [here](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md#required-models)!
* Do not add the LCM LoRA manually! Just choose "LCM" as Sampler (this is already default for Live)
