### ISSUE TITLE
Support for HandRefiner

### ISSUE THREAD

**Issue by LesnovBrascovitch** [Acly/krita-ai-diffusion#299]
Hello, thanks for your great krita plugin!

Is it possible to support HandRefiner in the future? I tried this with comfy ui and the result is quite impressive to generate correct hands.
https://github.com/wenquanlu/HandRefiner

Krita-ai-diffusion is already amazing to fix many broken images. Supporting HandRefiner would be heaven :D

**Comment by Acly** [comment]
Tried it out briefly yesterday, it does seem useful.

I'm still busy with some other work so it will have to wait a bit (or someone makes a PR in the meantime)

**Comment by Acly** [comment]
Part of [v1.13.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.0)

My experience so far, sometimes it can save some time, but unfortunately it's far from 100% reliable.
* Doesn't work for flat shaded styles. Those are relatively easy to fix by painting though, so not a big problem.
* Doesn't detect hands if they are _too_ mangled. Can't really blame it I guess :)
* Depth maps it generates are usually plausible (good anatomy), but often a bit too large? I had to scale some down.
* Biggest problem: **Event with a depth map, SD (1.5 and XL both) still is happy to generate terrible hands**
* The special depth-hand-inpaint model follows the hand shape well but the results often don't fit into the image at all (color, style, texture, detail...) - you have to use quite low strength, but it still often turns out blury.

Time will tell if it becomes a useful tool or I will just skip it and fix it manually (tedious but reliable)
