### ISSUE TITLE
Krita/Websocket Consumes outputs even after close

### ISSUE THREAD

**Issue by Grant-CP** [Acly/krita-ai-diffusion#310]
Not sure if this is a solvable at all, but I figured I would document it.

I'm running the local krita windows client, linux remote in Azure with A100 GPU for comfyui, port 8188,8189 are tunneled to the local machine via VS Code.

### Part 1

The undesirable behavior is that when I run a workflow via the browser I don't get any output in the browser.
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/8d4095ab-693a-4492-b83e-7c01ca75b066)

While the krita AI extension is running, that feels pretty reasonable. While the extension is running, I get an error code in client.log that looks like this: 
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/1ff778ab-c879-46ca-90a3-e1abe038f2d8)
Note that the prompt ID is not always constant:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/d8896d56-c87a-433a-9ab9-6101b16ee516)

I would expect either that workflows that run while krita AI is active would either emit the images to krita or they would emit to my browser. In fact, I think the most desirable behavior would be to have the images flow directly into krita. Perhaps this can be accomplished by bypassing the prompt_id check, or when the prompt_id check is failed to import the image anyway.

---

### Part 2

The main undesirable part is that even after krita is closed (and I wait an hour) I still cannot get images from the web interface. This is true even if I refresh the page, or open and close comfyui (ctrl +c). I can still submit runs, which I confirm via the queue and via the command line:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/b1980563-487f-4341-8f5f-7b10e20e0d0a)

However I do not see any output (see first image).

If I run comfyui on another port it works just fine, even while the original comfyui on 8188 is running/generating images into the temp folder:
![image](https://github.com/Acly/krita-ai-diffusion/assets/82120034/6643c3db-84e1-4bc4-a502-cb8a2f298921)

---

Not sure if there is much to be done on the websocket side. It is interesting that the queue in the web ui still updates, but the image outputs do not get delivered.

Finally, this isn't the largest issue, as I'm fine having one port dedicated to Krita AI and one port dedicated to the web ui. Having two processes work separately is a good practice anyway. Mostly wanted to document this behavior.

**Comment by Acly** [comment]
Sounds very strange, and I have a feeling it's somehow related to your setup.

ComfyUI server supports multiple clients, each with their own "client ID" (this is not the prompt ID). Each client enqueues their prompts with their unique client ID, and listens to their own private websocket messages.

In short: the web UI and Krita plugin should be able to use the same server, and _not interfere with each other at all._
(Small exception: the web UI does in fact show other client's jobs in the queue area for info, but otherwise ignores them.)

I often use both web UI + the plugin locally via the same server instance during development, and this works very well in practise. I haven't encountered anything like the behavior your describe.

**Comment by Acly** [comment]
> is the behavior of Krita "hearing" my generations something that shouldn't be happening?

Indeed that should not be happening.
