### ISSUE TITLE
Let us decide where the IP-Adapter model is located

### ISSUE THREAD

**Issue by Immac** [Acly/krita-ai-diffusion#332]
![image](https://github.com/Acly/krita-ai-diffusion/assets/3265190/b01e1847-d7a4-4a99-99f3-22bb8bdf5e44)
![image](https://github.com/Acly/krita-ai-diffusion/assets/3265190/218dd411-fc55-41af-b724-5b9e7e99c891)
![image](https://github.com/Acly/krita-ai-diffusion/assets/3265190/a1ff656a-8883-4a67-8bf7-30e6ac08efef)
Add it to the settings or something

**Comment by Acly** [comment]
Location is actually flexible as long as ComfyUI finds it and the filename matches. In case of clip-vision the filename includes the SD1.5 subfolder because its so non-discriptive, but you can still put the folder in other folders.

Anyway IMO it's reasonably flexible but there is discussion about a config file in #304

**Comment by Immac** [comment]
> Location is actually flexible as long as ComfyUI finds it and the filename matches. In case of clip-vision the filename includes the SD1.5 subfolder because its so non-discriptive, but you can still put the folder in other folders.
> 
> Anyway IMO it's reasonably flexible but there is discussion about a config file in #304

That's the thing, comfy did find the file, but it's named differently than what krita-ai-diffusion is expecting.
