### ISSUE TITLE
ControlNet Pixel Perfect mode

### ISSUE THREAD

**Issue by freecoderwaifu** [Acly/krita-ai-diffusion#333]
This is more of a question really, but possibly also a feature request. ControlNet in A1111 has a Pixel Perfect option that AFAIK auto adjusts the annotator to the resolution of the input image. In use, it helps results be sharper, especially helps with retaining smaller details, and overall avoids pixelization and low resolution artifacts from the annotator image.

The question is if it's already handled that way too in Krita Diffusion, if there's a way to reproduce it with existing options, or if it can be implemented as an option.

I've tried a couple of ways, but they all noticeably have the traits of low resolution annotators. These are all using the default 1x resolution slider recently added, though it also worked this way before it.

Base image made with Live Mode and LCM:
![2222222222](https://github.com/Acly/krita-ai-diffusion/assets/66507343/a72a5d52-16f3-459d-949b-9fc4c87e048f)

ControlNet Canny in Generate mode (DPM++ 2M SDE Karras, 40 steps, CFG 10, 100% strength)

![111111](https://github.com/Acly/krita-ai-diffusion/assets/66507343/0d652e45-8e8b-4eeb-8c0a-cf0176211de0)

ControlNet Canny in Live Mode (LCM 8 steps, CFG 2, 50% strength)

![3333333](https://github.com/Acly/krita-ai-diffusion/assets/66507343/96923268-782e-484a-9150-0b4537289c30)

ControlNet Canny in Live Mode (DPM++ 2M SDE Karras, 40 steps, CFG 10, 50% strength)

![6666666666](https://github.com/Acly/krita-ai-diffusion/assets/66507343/7b57b9f4-8a33-4db6-9590-4cc4186d2317)

By comparison this is what Pixel Perfect on vs off looks in A1111 (DPM++ 2M SDE Karras, 40 steps, CFG 10, 50% denoise)

Off:          
![a111111](https://github.com/Acly/krita-ai-diffusion/assets/66507343/cbc34227-0804-4765-bf3f-b5ecfdbb9359)

On:
![a22222222](https://github.com/Acly/krita-ai-diffusion/assets/66507343/3cb4c7ed-14a1-4896-bbe2-8838b3822df7)

The purpose of this is to help with adding back some detail that sometimes gets lost using Live Mode. LCM is great for speed, but in some checkpoints it tends to strip some of their shading and more stylized particularities, and tends to give a more "flat anime" look on them. These lost details can be added back using ControlNet and higher denoising, and other samplers. 

If this could be done with sharper annotators and all in Krita, it would be a great time saver. 

A1111 is great, but sometimes it's trickier to balance ControlNet, denoising and other parameters, to retain sharper details and not get more blended or "melting" details, especially on lineart, as is noticeable on the A1111 example in the shoes. 

This extension (and the nature of ComfyUI I guess) overall tends to retain smaller details much better and tends to provide sharper results, more noticeable in lineart, so it's much faster keeping it all in the same workflow: manual sketch > refine with Live Mode > refine shading and style with ControlNet.

**Comment by Acly** [comment]
Annotators work at image resolution. You can see the annotation result directly after all, you'd notice if it was lower (especially canny). What you see in your control layer is what is used, there is no further annotating going on when generating.

I believe in A1111 you control annotator resolution explicitly with a slider (default 512). It's possible that enabling "pixel perfect" automatically sets it to the input resolution. Haven't used it in a while.

Main effect of "pixel perfect" is a bit more subtle, at least how I understood it at the time. Sometimes images are resized to meet constraints:
* most annotators (but NOT canny) work at resolutions that are multiples of 64
* image diffusion works at resolutions that are multiple of 8

If your input image doesn't match (which is the case in this example), some kind of crop/resize takes place internally. This is also true for the Krita plugin. Pixel perfect mode mostly affects how this resizing works.

For your image, at 50% strength, there will be one resize (bilinear scaling) from 1308x1308 -> 1312x1312. This is not ideal but also makes very little difference in my experience. In particular I can't really reproduce the bad results you get for 50% strength, it looks as sharp as the input when I try it. Perhaps it could be improved slightly by using pad/crop instead of resize, but you can also easily avoid it by selecting a multiple-of-8 resolution.

At 100% strength situation is a bit different. Here it will use a 2-pass generation. The first pass runs at ~640x640. For this the canny image is probably downscaled by ControlNet implementation. This can be bad for canny, because it's supposed to have exactly 1px lines at all resolutions. I believe A1111 pixel perfect has a special scaling mechanism which preserves this better.

I tried to compare with and without "pixel perfect" downscale of the canny input:

Current result (no explicit downscale):
![ComfyUI_02939_](https://github.com/Acly/krita-ai-diffusion/assets/6485914/3879ecb5-b495-4bfd-a4e2-ec5812b15c7a)

With added explicit downscale for the 1st low-res pass:
![ComfyUI_02940_](https://github.com/Acly/krita-ai-diffusion/assets/6485914/49a106f4-05fa-4b94-afb7-5fd6cc212dd6)

You may get different/better results with your checkpoint/lora (I don't think mine understands the thick lines very well)

**Comment by freecoderwaifu** [comment]
That does make sense, especially about the resolution, I hadn't even considered that. Thanks for the clarification 👍.
