### ISSUE TITLE
[Feature Request] - Model Management Tab

### ISSUE THREAD

**Issue by raniaamina** [Acly/krita-ai-diffusion#337]
The checkpoint and Lora models installed in the current version can be well organized because they can be grouped in folders. Furthermore, is it possible to add features (I imagine a stone tab) Model Management? The function of this feature;

- Determine which models of either checkpoint or loras you want to activate or deactivate
- Set the predict of predefined attributes, several models come with certain settings, such as, clip skips, weight, sampler, step, CFG, and trigger words, etc. It would be very helpful if we choose this checkpoint / lora preset model can be automatically selected / filled.

I know, it's not easy to add the feature, but i just wanna share this idea for next development if possible.

**Comment by Acly** [comment]
Is this different from the request in #280?

> Set the predict of predefined attributes, several models come with certain settings, such as, clip skips, weight, sampler, step, CFG, and trigger words, etc. It would be very helpful if we choose this checkpoint / lora preset model can be automatically selected / filled.

This is the point of style files though - they store all this information. It doesn't make sense to me to create another mechnism which does the same. To be sure the style management could be extended (maybe a duplicate button would already help, or some kind of template/override mechanism).

Lora management tab could be separate so Loras can be composed more easily.

**Comment by jacobEAdamson** [comment]
I'm wondering... Maybe it makes sense to have Loras and Lycos be able to be configured separately from the base checkpoint. Like, still use the style files, but have a section for configuring the lora/lyco parameters, and then be able to use those pre-configured loras/lycos in the checkpoint style config. And then you might also be able to expose them via the prompt window (maybe something similar to how control net options are configured). One thing you might be able to do would be to allow a user to configure certain prompt additions that would be automatically entered when using that Lora. For example, maybe I have a lora to add elf ears, but usually when using the lora, I want to enter "elf ears" into the positive prompt, and "cat ears" into the negative prompt. Instead of having to enter that every single time I add that to a checkpoint style config, I could configure it at the Lora level, and then when including that in a checkpoint, have those items automatically added into the prompts (maybe something like {lora_0_prompt} so you can control the location they appear in your style).

Then it would be easier to add and remove loras as wanted during prompt generation. One thing that's a little un-intuitive right now (for me at least) is that if I want to include a specific concept Lora for my prompt, I have to go in, modify my base style, and then go back and update the prompt. It would be nice if we could reference loras directly in the prompt somehow, or at least near to the prompt without having to edit the base style

**Comment by jacobEAdamson** [comment]
Wait, I see some code that automatically parses loras in the prompt! So, I think that answers one of my questions

**Comment by raniaamina** [comment]
> Is this different from the request in #280?
> 
> > Set the predict of predefined attributes, several models come with certain settings, such as, clip skips, weight, sampler, step, CFG, and trigger words, etc. It would be very helpful if we choose this checkpoint / lora preset model can be automatically selected / filled.
> 
> This is the point of style files though - they store all this information. It doesn't make sense to me to create another mechnism which does the same. To be sure the style management could be extended (maybe a duplicate button would already help, or some kind of template/override mechanism).
> 
> Lora management tab could be separate so Loras can be composed more easily.

I think there are similarities from a functional perspective, it's just that I specifically hope that there are predefined settings, especially for lora, so that for example when I choose a lora, those settings (step, cfg scale, sampler, trigger word, etc., which usually have been tested and have best results) can be automatically loaded without having to reset the settings again. but whatever, I really appreciate your response on this.
