### ISSUE TITLE
[ERROR] : Server is missing one or more stable diffusion checkpoints.

### ISSUE THREAD

**Issue by Mithun-sk** [Acly/krita-ai-diffusion#358]
After installing when i start the server, i get the error as such.
![image](https://github.com/Acly/krita-ai-diffusion/assets/68943373/2120981b-07f4-414c-a4ac-bcf6f2c62c66)

i am also not able to select the checkpoint from dropdown(the dropdown tab is empty)
![image](https://github.com/Acly/krita-ai-diffusion/assets/68943373/d6891cb5-6ac3-45ab-b302-6fd69bad2b2b)

**Comment by Mithun-sk** [comment]
[client.log](https://github.com/Acly/krita-ai-diffusion/files/14050893/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14050894/server.log)

**Comment by Acly** [comment]
Hm strange. Can you check/post the output of http://127.0.0.1:8188/etn/model_info while the server is running?

**Comment by ReClaim-UrbanGamification** [comment]
I am having the exact same issue. Also, Local Server managed by the Krita plugin...

**Comment by eyesonmeuk** [comment]
same errorQQ

**Comment by Acly** [comment]
Alternative download links (these are also official, but no login required):
* Realistic Vision: https://huggingface.co/SG161222/Realistic_Vision_V5.1_noVAE/resolve/main/Realistic_Vision_V5.1_fp16-no-ema.safetensors
* DreamShaper: https://huggingface.co/Lykon/DreamShaper/resolve/main/DreamShaper_8_pruned.safetensors

You might have to update the default styles because the filenames are different.

**Comment by ReClaim-UrbanGamification** [comment]
It worked! Thank you so much =)

**Comment by Mithun-sk** [comment]
After a lot of troubleshoot even I eventually noticed the file size was small and installed those files, and now it works! Thankyou for your quick response and solution.

**Comment by Acly** [comment]
Exchanged the installer's links in [v1.13.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.13.1) so the downloads should work again.
