### ISSUE TITLE
Selection Fill & Expand for Stable Diffusion XL

### ISSUE THREAD

**Issue by hansnolte** [Acly/krita-ai-diffusion#397]
Does SD XL now have the better Selection Fill & Expand (Fooocus) or is it “just” on par with SD 1.5?
Is Fooocus also available for SD 1.5?
Which modules now work with SD XL?
Does SD XL even work on a GTX 1070 with 8GB VRam?

Best regards
Hans

**Comment by Acly** [comment]
I'd say it's roughly on par, but it's hard to compare because it always depends on the content. SD XL probably covers a wider range.

The Fooocus inpaint model is SDXL only.
SD1.5 still has better control net support.
As to whether it works on 1070, you will have to try out. Basic stuff should work even with 6GB, but some of the advanced features may run out of VRAM.

**Comment by hansnolte** [comment]
Thank you for your answer, Acly.

Then I'll give SDXL a try.

Many greetings and a big thank you for your great work
Hans
