### ISSUE TITLE
I'm facing a server issue.

### ISSUE THREAD

**Issue by digbmn** [Acly/krita-ai-diffusion#416]
I've downloaded everything that was required. After that, the local server is not running; in addition, it is showing something, to which I've attached a screenshot.
![Screenshot_1](https://github.com/Acly/krita-ai-diffusion/assets/124176059/d09f0f37-5dc7-4a5c-b779-f6c8913ae88c)

**Comment by Acly** [comment]
The error says that some process is already running and using port 8188. It might be another ComfyUI server or something else.
Related: #390, #196, #81

**Comment by digbmn** [comment]
> The error says that some process is already running and using port 8188. It might be another ComfyUI server or something else. Related: #390, #196, #81

Now what should I need to do?

**Comment by Acly** [comment]
Try to log off to shut down any leftover processes. If that works, also consider updating the plugin to 1.14.1, it solves issues with leftover processes.

If it doesn't fix it, you can try changing the port. Read the other issues for more info, it's hard to tell because it's specific to your system.
