### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by nakanakapoi** [Acly/krita-ai-diffusion#44]
I usually run four machines simultaneously. Is there a way to run four instances of krita with this plugin, each connected to different server, preferably with only one krita install?.

**Comment by Acly** [comment]
So you run 4 servers on different machines, and want 4 instances of Krita using the same installation on one machine to be connected to each of the 4 servers?
I think it's not possible, because Krita doesn't allow multiple instances. There is some workaround maybe if you have different installs: https://krita-artists.org/t/krita-5-two-instances-at-the-same-time/35770

I'm not sure what your use case is though. Are you really actively working on 4 different images in parallel? If all you want to do is pump out more images for different initial generation, I would just use Comfy web UI or some other front-end directly. 

It would be cool though to have one Krita instance connected to all 4 servers for thoughput. You'd probably want to implement some kind of aggregation middle-server for that...

**Comment by nakanakapoi** [comment]
Yes, I know it is impossible but I need to ask just in case. Multiple comfy web ui is the only way, but I have to open krita anyway to do the final editing. I work with something niche that require huge iteration.

**Comment by nakanakapoi** [comment]
I found out the best alternative is to run krita locally in each machine, then use remote desktop. I latency in 5Ghz wifi is still acceptable. Even pen pressure work if you set krita to use windows ink.
