### ISSUE TITLE
Failed to download Ultimate SD Upscale

### ISSUE THREAD

**Issue by amoxur** [Acly/krita-ai-diffusion#484]
When I try to use install a ComfyUI server by "Local server managed by Krita plugin"
![20240310214043](https://github.com/Acly/krita-ai-diffusion/assets/79034773/aef30138-b74b-458a-a354-34df865cee0d)
I got this :
Error：Failed to download https://github.com/Acly/krita-ai-diffusion/releases/download/v0.1.0/ComfyUI_UltimateSDUpscale-6ea48202a76ccf5904ddfa85f826efa80dd50520-repack.zip

**Comment by Acly** [comment]
Link works for me, are you able to download it via browser? Is it possible something is blocking it?

**Comment by adamulp** [comment]
This happens for me too, it looks like an issue with github redirects:
https://github.com/orgs/community/discussions/50966

If I try to download from the browser or using curl, the link works fine, and the download completes, but when wget fails, I can see that there's a redirect to objects.githubusercontent.com. Since other github urls are working fine for this project, I don't guess that it's an issue with the python library being used to download things either. I was able to remove this from the resources.py file, manually download, extract to the proper directory, add the thing back to resources and reinstall the plugin, which completed the install. There's a floating point exception when I do this, which may or may not be related to the manual install hack.

**Comment by Acly** [comment]
I just checked and it still works for me - redirects are followed. Maybe it was temporary? Was there a more detailed message in the log?

In the long run I might mirror these files, but it's a bit of work to automate it.

**Comment by Acly** [comment]
The plugin runs in Krita's embedded Python, no extra dependencies allowed, so options are limited. Also sub-process makes it much harder to display progress in the UI.

It might just be that there's an issue with GitHub's SSL certificates, wouldn't be the first time. Other download tools are less strict about it.

Next version might get rid of the UltimateSDUpscale dependency, so maybe not worth thinking about this particular issue too much.
