### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by CapCG** [Acly/krita-ai-diffusion#49]
Hi all!
This situation will generate an error, as I understand it, when sending a request to the server.
Tried with Krita version 5.2 and plugin version 1.5 and Krita 5.21 plugin 1.6
The result is the same, the installation was without any errors.
What could be the problem?
![image](https://github.com/Acly/krita-ai-diffusion/assets/150868993/9f06f491-c0a4-4982-8924-0cf3cafad81d)
![image](https://github.com/Acly/krita-ai-diffusion/assets/150868993/b31ab96b-75ac-42b0-8397-4a8bc1fee0a4)

**Comment by Acly** [comment]
Hi, could you share the server.log file? You can find it via "View log files" in connection settings. That will provide some more information on what caused the error.
Does this always happen, or only in particular situation (with certain selection or strength)?

**Comment by CapCG** [comment]
I understood what the situation was, for SD 1.5 models, 16GB of memory is enough, taking into account that nothing else is running on the computer, a browser, etc., and then it generates.
But if you try to launch XL, that’s all)) black screen and error.

**Comment by Acly** [comment]
You mean the same error as posted initally? It's a bit surprising since that validation error usually appears before anything happens.
Regarding system memory, SD 1.5 usually stays below 12GB for me, but XL can go up to 20GB (when doing 100% strength + selection). Probably depends on OS and image resolution too. So yes it might be an issue.
