### ISSUE TITLE
Cinematic Photo (XL) keeps giving server execution error

### ISSUE THREAD

**Issue by feureau** [Acly/krita-ai-diffusion#519]
Hi,
Running Cinematic photo (XL) keeps giving me this error:

Server execution error: Expected query, key, and value to have the same dtype, but got query.dtype: struct c10::Half key. dtype: float and value.dtype: float instead. 

Steps to reproduce is simply just to generate an image using Cinematic Photo (XL).

Plugin ver 1.15.0
Krita is 5.2.0
GPU is NVidia 1070. 

Perhaps this is due to the float feature that comes with newer RTX cards?

Error also happens when controlnet "Face" and/or "reference" is enabled.

![image](https://github.com/Acly/krita-ai-diffusion/assets/290044/0ca53903-9336-4676-b6a5-155eab3fe12a)

**Comment by Sil3ntKn1ght** [comment]
I had this error twice first i believe there was a corruption in the .json for XL i never trided just deleting and re making i download the whole model again as per video. sorry fast forward i know i ramble.
https://youtu.be/xh-4YUr1F4U?si=iedFaLC9unVc_sVb

second was in the new 1.15 i assume due to the gtx card as my rtx3060 does not have this error, i fixed it via whats shown in video.
https://youtu.be/FzvaNV9fQ3o?si=JqTu4T17RqUBK6Ks

i do the videos as memory log for myself at the same time share as might help other, plus dyslexic so reading and writing to explain how i fix thing is harder than doing this.
anyway hope it helps you to get creating.
