### ISSUE TITLE
Local managed server fails to install on Python 3.12

### ISSUE THREAD

**Issue by asluizh** [Acly/krita-ai-diffusion#576]
Because there is no mediapipe available for Python 3.12, this plugin will not be able to finish the installation, with the error: 

```
Exception: Error during installation: ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

Additionally, the plugin will not run on a folder that it itself created when it fails, so that no workaround is possible (for example, by recreating the env with the appropriate python version, and manually installing mediapipe).
[client.log](https://github.com/Acly/krita-ai-diffusion/files/14839892/client.log)

**Comment by Acly** [comment]
Yes, but that's documented in installation instructions... first all dependencies need to support 3.12.

Refusing to install into existing "foreign" directories is by design to avoid accidentally overwriting data. It shouldn't be needed though, the installer prioritizes `python3.11` and `python3.10` commands, so you should be able to install even if your default `python3` is 3.12
