### ISSUE TITLE
Regarding version 1.16.1, the edges of mask drawing are too sharp.

### ISSUE THREAD

**Issue by qingzhenbiaojie** [Acly/krita-ai-diffusion#601]
Hi Ackerly：
   a suggestion, in version 1.16.1, the mask tool is not as easy to use as in 1.15.0. The edge effect after drawing the mask in 1.16.1 is not good and too sharp. Parts of the painted pattern require repeated rubbing at the edges. Hopefully improved to be consistent with the feathering of mask drawings in 1.15.0.
![微信截图_20240409181139](https://github.com/Acly/krita-ai-diffusion/assets/156321695/1d8c8b53-947a-497f-a02d-eaad5c0d34f2)

**Comment by Acly** [comment]
There is less blending in latest versions, because the denoising strength is smoother at edges. So the opaque part of the image already has a gradual transition.

Having a smooth transition in the generated image is usually better. The alpha-blending is not really a good solution (images are only on top of each other, they don't really transition well). It was/is just there because of visible seams otherwise.

If you think the new behavior isn't working well, please post images of that.
