### ISSUE TITLE
Problem with storage location

### ISSUE THREAD

**Issue by F1pa** [Acly/krita-ai-diffusion#620]
Hello, I want to download a plugin for AI tools, but even If I select a folder on the drive where is a 100gb space it tells me there is no space... If I open the file location It is always selecting the main drive. Sending you a screenshot... Please try to fix that, thank you 
It always create a new folder in local on the main drive... even if I change it 

![image](https://github.com/Acly/krita-ai-diffusion/assets/167126740/1ea9ec6f-b8b9-4df7-85ce-be7c7561c55c)

**Comment by Acly** [comment]
It works fine for me, what steps are you doing exactly?

The button for opening file location only works for existing folders I think, this might be why it opens in the default location.

**Comment by F1pa** [comment]
1) I set up the main Krita folder path
2) I want to install the local server (every path I want to be on the D drive)
3) I got ERROR that on the disc is not enough space 
![problem](https://github.com/Acly/krita-ai-diffusion/assets/167126740/7b89a0c3-01b8-4ce4-bdf9-2c9bbcb0118a)

**Comment by Acly** [comment]
But does it actually install into the server folder on C:\ or is it empty?
Can you check the client.log file (in logs folder), it should confirm the destination.

Note that even if you install into different location, probably some space on C: is required because of system-wide Python/PIP cache. This might be the reason you run out. I think you can set `PIP_CACHE_DIR` environment variable to a different directory to change it.

**Comment by F1pa** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/167126740/70d25fad-c2ec-4117-af0d-d0509f00d210)
@Acly This is the log

**Comment by Acly** [comment]
It shows the correct path, so I'm pretty sure there is nothing wrong with the installer logic. You probably run out because of the cache.
