### ISSUE TITLE
Assistance with the new sampler selection

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Acly/krita-ai-diffusion#633]
The checkpoint I use most was trained with Euler_a, and by default, this new update only includes Euler, which is now called Realtime Lightning? Unless I am _severely_ misunderstanding how this works, _which is probably the case_, sampler selection just got unnecessarily more complicated.

![image](https://github.com/Acly/krita-ai-diffusion/assets/60951301/705c94ae-d8f9-4c29-b7f6-8e3fed615edc)
![image](https://github.com/Acly/krita-ai-diffusion/assets/60951301/0eef8fad-01a8-4832-a737-7efb97f727c7)

I had a look at the json for custom presets. I'm confused on the formatting for adding additional samplers, as there's only one example there. Only having a single entry in the file by default does not tell you how to properly separate multiple entries.

I just need instructions on how to actually use this. Any assistance is appreciated. Thank you.

**Comment by Acly** [comment]
There were a few options which are not among the built-in presets now, like Euler A - in that case yes, it got more complicated. But there are also a lot of options that weren't possible before now, so it's a small trade-off.

The built-in presets are here: https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/presets/samplers.json
You can also find them in the install dir.

After you edit the user presets (the file you have open), you have to restart to see the new options. The example should appear in the drop down.

Regarding sampler names, I kind of assumed people who'd be interested in tweaking samplers are familiar with ComfyUI, but maybe not a correct assumption :)
You probably want sampler `euler_ancestral`  and scheduler `normal`.

Yes comments would be nice. I had some, but then it was trickier than anticipated because JSON doesn't officially support comments and the sampler/scheduler names are only available once connected. Definitely doable though.

**Comment by JENOVAAbsolute** [comment]
> There were a few options which are not among the built-in presets now, like Euler A - in that case yes, it got more complicated. But there are also a lot of options that weren't possible before now, so it's a small trade-off.
> 
> For reference, the built-in presets are here: https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/presets/samplers.json You can also find them in the install dir.
> 
> After you edit the user presets (the file you have open), you have to restart to see the new options. The example should appear in the drop down.
> 
> Regarding sampler names, I kind of assumed people who'd be interested in tweaking samplers are familiar with ComfyUI, but maybe not a correct assumption :) You probably want sampler `euler_ancestral` and scheduler `normal`.
> 
> Yes comments would be nice. I had some, but then it was trickier than anticipated because JSON doesn't officially support comments and the sampler/scheduler names are only available once connected. Definitely doable though.

That link was helpful.

Yes, I got json and another config format mixed up. I remembered that comments aren't supported in json, so I edited that out of my post soon after I made it. My mistake.

Also, I apologize if I came off as passive aggressive or rude. That was not my intention.

Much appreciated for the help. I'll mark this closed as completed. Have a good one.
