### ISSUE TITLE
Can't load modules after upgrade to 1.17.1

### ISSUE THREAD

**Issue by Codeschreibaer** [Acly/krita-ai-diffusion#665]
I get greyed out module in plug in manger, even after i delted the directory totally.
(For total information: Befor  idid this i copied the 1.17 directory to my desktop, meanwhile everything it is deleted. )

I followed an old issue where you recommended deleting line 7-13 of the __init__.py file.

After that i got:
![Screenshot AI diff 1 17 1](https://github.com/Acly/krita-ai-diffusion/assets/71262617/41ab4dfe-96d9-4c69-80dd-638b6dadf79f)

**Comment by Acly** [comment]
It looks like it cannot load the settings. They are usually in `...AppData\Roaming\krita\ai_diffusion\settings.json` - try delete/move the file and it should make a new one with defaults.

Did you edit it manually recently? If you post the file contents it might tell more.

(Also labeling as bug because this error should probably be recoverable instead of failing to load the plugin)

**Comment by Codeschreibaer** [comment]
Thanks that helped. Solved. Under 1.17.0 still today i tested //"server_arguments": "--dont-upcast-attention --force-fp16",
and commented it out. It was always working after each modifying step. (I did this because this solved my face ip problem with sl  Models.) Occurred as error first under 1.17.1

Greetings from Cologne
Jochen

**Comment by Acly** [comment]
Interesting. I have no idea why that worked before, comments aren't allowed in JSON by default. Although I might as well enable that for future, it's useful sometimes.

**Comment by Codeschreibaer** [comment]
It allowed me to "toggle" between face 1.5 and XL. So comments would be nice. Even better:  to make this arguments only working for xl (though not knowing how.)
