### ISSUE TITLE
krita python plugin manager problem

### ISSUE THREAD

**Issue by TryhardTechy** [Acly/krita-ai-diffusion#67]
I was following the instructions for a custom comfy server as I already have comfyui running locally. everything was fine up until it got to the Krita stages. I put the plugin files into the specified folder and I clicked the check in the python manager inside of Krita and it is for some reason greyed out with the error 

ModuleNotFoundError: No module named 'ai_diffusion.websockets.src' 
could not import ai_diffusion

**Comment by Acly** [comment]
websockets is a required 3rd party module. It is packaged alongside every [release](https://github.com/Acly/krita-ai-diffusion/releases).
If it's missing, that's maybe because you downloaded a snapshot via GitHub Code > Download ZIP? GitHub does not include sub-modules there, and I can't influence that.
