### ISSUE TITLE
Less sharp inpaint because of unwanted bilinear scaling

### ISSUE THREAD

**Issue by Danamir** [Acly/krita-ai-diffusion#679]
Not sure if this is a bug or by design but when doing a smallish inpaint (ie. a face), the `refine_region` method does this at the start : 

```Python
in_image = scale_to_initial(extent, w, in_image, models)
```

This method in turn uses `extent.initial_scaling`, which by default executes the following code : 

```Python
        if ratio < 1:
            return ScaleMode.resize
```

This is good for masks, but not for the source image as it becomes blurry because of the bilinear scaling used with `ScaleMode.resize` . The inpainted region is then not as sharp as it could. Shouldn't `ScaleMode.upscale_fast` be used here ? 

I tried altering the code of `extent.initial_scaling` and the inpaint are indeed much sharper after the modification, at a minimal computing cost.

Source region before resize : 

![source](https://github.com/Acly/krita-ai-diffusion/assets/15424198/63d012d6-3310-4c32-90a7-975dd6a17b36)

| Scale method | Scaled Image | Rendering output | Scaled output |
| --- | --- | --- | --- |
| Bilinear (ie. `ScaleMode.resize`) | ![bili_1](https://github.com/Acly/krita-ai-diffusion/assets/15424198/ab060c1b-7d4c-4d48-b329-259b94d2669f) | ![bili_2](https://github.com/Acly/krita-ai-diffusion/assets/15424198/9da0798d-d056-40c0-b801-2f51ae230dc3) | ![bili_3](https://github.com/Acly/krita-ai-diffusion/assets/15424198/e99264a1-4317-440c-ae03-c3833b2baf17) | 
| `OmniSR_X4_DIV2K` (ie. `ScaleMode.upscale_fast`) | ![omni_1](https://github.com/Acly/krita-ai-diffusion/assets/15424198/f46a1b33-ed43-4582-ab62-0f7450ae1e42)|![omni_2](https://github.com/Acly/krita-ai-diffusion/assets/15424198/b196415c-6172-4542-b0fb-fa2a5feeae97) | ![omni_3](https://github.com/Acly/krita-ai-diffusion/assets/15424198/5ad36f8a-8873-436c-a907-4bebebfa762d)| 
| `UltraSharp 4x` | ![ComfyUI_temp_dbsie_00004_](https://github.com/Acly/krita-ai-diffusion/assets/15424198/c55ed8a5-0ad8-4ff8-ba25-8118e5140cc0)  | ![ComfyUI_temp_sffrd_00003_](https://github.com/Acly/krita-ai-diffusion/assets/15424198/039d0ab6-d533-4afa-a4ad-4a38bb7a9441) |![ComfyUI_temp_zclva_00004_](https://github.com/Acly/krita-ai-diffusion/assets/15424198/ac98a918-b425-4f29-aeec-c7f0bffe230a) | 

(I added `UltraSharp 4x` to give an example of an even sharper scaler).

**Comment by Danamir** [comment]
On the same subject, when adding `ImageScale` nodes, we use the `bilinear` algorithm by default. I would argue that using `lanczos` (or ar least `bicubic`) is preferable in almost every case, it is still not as sharp as using an upscale model, but way better than bilinear.

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/87c3164a-8570-4c22-8b68-4a1d39b19c11)

**Comment by Danamir** [comment]
In fact the final `ImageScale` of the workflow is also using `bilinear`, which causes aliasing when scaling down, mostly visible on anime clear lines. In this instance the `bicubic` method is as bad as the `bilinear` one, but the results with `lanczos` are very nice.

I think we should simply update all calls to `lanczos` for downsampling and upsampling. Do you think there is a downside to this ? 

In the following pictures pay close attention to the dark hair lines on light background to see visible aliasing :  

| Scaler | Downscaled image |
| --- | --- |
| `bilinear` | ![bilinear](https://github.com/Acly/krita-ai-diffusion/assets/15424198/0bcfe6ed-fad4-4e65-8065-5850bb518092) |
| `bicubic` | ![bicubic](https://github.com/Acly/krita-ai-diffusion/assets/15424198/9237a97f-771d-4e77-9ac5-3c4dc88a9296) |
| `lanczos` | ![lanczos](https://github.com/Acly/krita-ai-diffusion/assets/15424198/40ab78af-9233-475d-8ba9-9521a990266e) |

**Comment by Acly** [comment]
So this is the case where the image (region) size is smaller than the checkpoint resolution. The workflows becomes "Upscale -> Diffuse -> Downscale". The main point of this mechanism is to avoid bad generation for low resolutions, since checkpoints generally can't handle them and produce garbage. It's not meant to sharpen results in the area, ideally they should be consistent with the lower resolution used by the canvas. That's why AI upscaler is not used here - if the render result appears a bit blury, that may actually be ok, because it's downscaled afterwards. Also AI upscalers can have detrimental effects too, so I want to be careful with using them automatically unless >50% diffusion happens afterwards, or it's explicitly desired.

Viewed from another angle, if you wanted sharper results of better quality, the recommendation should be to increase canvas size, using upscaler of your choice. Then there will be no implicit upscale before diffusion, and more importantly, you get to keep the full resolution render output, instead of throwing away most pixels. This is especially important for follow up refines, the upscale/diffuse/downscale workflow will always have detrimental effects, regardless of which upscaler is used.

I do very much agree with using Lanczso over Bilinear. I think it should mostly fix the case where bilinear introduces additional blur on top of the resolution change. It wasn't available in Comfy when I initially implemented this, and since got drowned somewhere on the TODO list...

**Comment by Danamir** [comment]
> I do very much agree with using Lanczso over Bilinear. I think it should mostly fix the case where bilinear introduces additional blur on top of the resolution change

Yes, I think it would be a sufficient fix. I wasn't aware of the problem until after having posted the first issue and continued poking around in the workflow debug. 

> Viewed from another angle, if you wanted sharper results of better quality, the recommendation should be to increase canvas size, using upscaler of your choice.

I tend to work at lower resolution, and using the inpaint as a detailer tool. But I get that it is not a recommended usage, so no worries if it is not fully supported in the plugin.

Using an upscaler model is kind of an overkill, but I still like the idea because it has a comparable feel to using the detailer nodes in ComfyUI. Fortunately I keep a custom fork for those kind of hacks. 😁

**Comment by Acly** [comment]
> I tend to work at lower resolution, and using the inpaint as a detailer tool.

There was this issue where I tried to convince some A1111 veterans that it's an anti-pattern. Mostly without success I think ^^

It's interesting because there's also people here who come from Krita/Photoshop and are new to SD, and of course the canvas or photo is like 6000x4000, it's normal, and why should they downscale their painting or photos for SD? And I think it's a good point. Different mediums work at different resolutions, but the canvas should match the highest to avoid loosing information. And there should be no downscales for the same reason.  SD generation can be upscaled where needed, because native resolutions that high are often just not practical - but preferably not the other way round.

Ideally the only point where you downscale anything is the final "export to PNG for reddit post" step. And I'd like to make that more realistic, but admittedly not quite there yet.

(Also those detailer nodes!, ppl make them downscale the high res result they already computed to insert it into tiny image... and then upscale that afterwards?!? like, it makes so much more sense to do it the other way round...)

**Comment by Drakosha405** [comment]
> There was this issue where I tried to convince some A1111 veterans that it's an anti-pattern. Mostly without success I think 
> 
> It's interesting because there's also people here who come from Krita/Photoshop and are new to SD, and of course the canvas or photo is like 6000x4000, it's normal, and why should they downscale their painting or photos for SD? And I think it's a good point. Different mediums work at different resolutions, but the canvas should match the highest to avoid loosing information. And there should be no downscales for the same reason. SD generation can be upscaled where needed, because native resolutions that high are often just not practical - but preferably not the other way round.
> 
working with a large image is always good, but processing (encoding\ decoding) such images is too resource-intensive for many users of non-top computers. right now I have found this add-on and the first samples showed good results for me and high speed, while maintaining the idea of working at maximum resolution.
https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch

If it were possible for your application to implement such a feature, I believe many users would appreciate it. I am interested in hearing your thoughts on whether there are any significant drawbacks in this process.

**Comment by Acly** [comment]
It has worked like that from day 1 - you don't really need those nodes, they just make it more convenient when using Comfy's UI. As for drawback, a smaller context is faster but means you loose coherence with the rest of the image.

**Comment by Acly** [comment]
[1.17.2](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.2) now uses Lanczos for all image scales not handles by upscale model. Masks use bilinear still.
