### ISSUE TITLE
[Question] Does this plugin inpaint at full resolution?

### ISSUE THREAD

**Issue by JasonS09** [Acly/krita-ai-diffusion#72]
Hello! First off, nice work with this plugin. I really like the interface and I would like to use it more. However, having a low vram card myself makes me wonder if this plugin is optimized for use. I would like to know if this uses inpaint at full resolution, so I am able to work with any canvas size knowing generation will only take the required part of the canvas when inpainting. It's also useful for adding details with more control. Right now I'm not clear if this happens or not and it's a deal breaker for me.

**Comment by Acly** [comment]
Hi! There are two inpaint pipelines which differ in complexity:
* less than 100% strength (img2img) - this one is fairly simple, it takes the masked area, applies small grow & feather (configurable), adds a bit of padding (also configurable), and then only generates the area around the selection. VRAM use is independent of image size, only selection size matters.
* 100% strength (true inpaint) - this is challenging to make things seamless. It will downscale a large part of the image to "optimal" size (eg 512~768 for SD1.5), then inpaint using the whole area to have sufficient context. Then crop down to a smaller region around the mask, upscale to the target size, and img2img at low denoise. Basically 2-stage high-res fix workflow, but only upscaling the relevant masked part. This is _generally_ also nice for VRAM, except that it's also using IP-adapter to improve results, which is expensive. Really improves results though.

**Comment by Pauan** [comment]
@Acly Could this information be added to the website documentation somewhere?

While working on an image, I was extremely confused, because inpainting a small selection is using *far* more VRAM than generating an entire image.

I can generate an entire 638 x 1110 pixel image without any issues, it uses up 12.5 GB of VRAM.

However, when I try to inpaint with a 220 x 220 pixel selection, it uses up over 16 GB of VRAM and it runs out of memory and crashes:

```
torch.OutOfMemoryError: HIP out of memory.
Tried to allocate 720.00 MiB. GPU 0 has a total capacity of 15.98 GiB of which 672.00 MiB is free.
Of the allocated memory 14.50 GiB is allocated by PyTorch, and 469.41 MiB is reserved by PyTorch but unallocated.
If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.
See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Got an OOM, unloading all loaded models.
```

(Using `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` didn't seem to change anything)

If I reduce the inpaint strength below 100%, then the inpaint uses 12.5 GB of VRAM, as expected.

It's very unintuitive that 100% strength inpainting with a tiny selection uses *more* VRAM than generating a full size image.
