### ISSUE TITLE
Generated images are just black

### ISSUE THREAD

**Issue by jmgpp** [Acly/krita-ai-diffusion#783]
Hi, I setup a local server following the installation guide and everything seems to be setup correctly. But after I give a prompt and "Generate" it takes about a minute to create 4 all black alternatives. 
I have and M1 Macbook with 8 GB of RAM, so I assummed it would take forever to generate, 1-2 minutes is pretty fast but it doesn't create anything. Can it be the lack of RAM? Thanks!

<img width="1440" alt="Captura de pantalla 2024-06-11 a la(s) 15 52 51" src="https://github.com/Acly/krita-ai-diffusion/assets/2017129/48010288-0e58-4152-b8f4-96df7f0578a5">

<img width="909" alt="Captura de pantalla 2024-06-11 a la(s) 15 59 30" src="https://github.com/Acly/krita-ai-diffusion/assets/2017129/660440ba-3230-4e6e-bfd3-a8ac6db1fe85">

**Comment by itchymitchy** [comment]
I have the same issue, can anyone help?

**Comment by itchymitchy** [comment]
When I install then use the XL image generator I get an image.

**Comment by haveamission** [comment]
> Hi, I setup a local server following the installation guide and everything seems to be setup correctly. But after I give a prompt and "Generate" it takes about a minute to create 4 all black alternatives. I have and M1 Macbook with 8 GB of RAM, so I assummed it would take forever to generate, 1-2 minutes is pretty fast but it doesn't create anything. Can it be the lack of RAM? Thanks!
> 
> <img alt="Captura de pantalla 2024-06-11 a la(s) 15 52 51" width="1440" src="https://private-user-images.githubusercontent.com/2017129/338712096-48010288-0e58-4152-b8f4-96df7f0578a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NzA3MjIsIm5iZiI6MTcxODY3MDQyMiwicGF0aCI6Ii8yMDE3MTI5LzMzODcxMjA5Ni00ODAxMDI4OC0wZTU4LTQxNTItYjhmNC05NmRmN2YwNTc4YTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDAyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMyMzBkMDBlNmYzNTM4ZWExMGY5NzA3OWU4MWQwYjE1NDk2YWY4Njg3YzcxMWIwOTEzZDdhMDFhZTRiOTkyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2M0ZFj2vwR_DlqcSl56EEk20sx7Ck3w-r8PR7FUa5Sw"> <img alt="Captura de pantalla 2024-06-11 a la(s) 15 59 30" width="909" src="https://private-user-images.githubusercontent.com/2017129/338712434-660440ba-3230-4e6e-bfd3-a8ac6db1fe85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NzA3MjIsIm5iZiI6MTcxODY3MDQyMiwicGF0aCI6Ii8yMDE3MTI5LzMzODcxMjQzNC02NjA0NDBiYS0zMjMwLTRlNmUtYmZkMy1hOGFjNmRiMWZlODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDAyNzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTliOTY1ZTRlMjVjMDYyNGM5MzQ4OTA4ZGRlNTIyZjYyYzQ2YmQ3MDM3YmFjNGVmMjMzNGY5MDI4ODYzYTlmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pYezbaw6HPdpA0M-KjJ8DkuS1s5kp254RM--sSrcr8o">

Definitely not due to lack of RAM. I have an M1 Max with 64 GB of RAM and I'm seeing the same problem. Initial image gen works great, but subsequent expansion, fill, etc, does not

**Comment by haveamission** [comment]
I was able to get images generating again by selecting "add a control layer", which is non-optimal, but may lead us to a solution

**Comment by haveamission** [comment]
Seems like it happens when there's transparency for the background (the checkered gray background). When I painted it with white, it worked fine

**Comment by Acly** [comment]
> Seems like it happens when there's transparency for the background (the checkered gray background). When I painted it with white, it worked fine

That sounds like you used transparent/black image as input though. ai generation ignores alpha/transparency entirely, it's same as black.

The original post sounds more like a issue with recent update of macOS/pytorch, but I can't find a lot of information on it.

**Comment by haveamission** [comment]
`That sounds like you used transparent/black image as input though`

No, I'm not using img2img at all (at least as far as I can tell, I've only used Krita for a few days, but I'm broadly familiar with how SD works and was running my own ComfyUI workflows beforehand.

The workarounds I'm mentioning are only working in a few scenarios, sometimes they're not. Like right now I'm trying to do some inpainting on some sky with a new prompt, and the entire output is black. There isn't any transparency or blackness in the image at all.
<img width="1607" alt="Screenshot 2024-06-18 at 12 10 53 PM" src="https://github.com/Acly/krita-ai-diffusion/assets/10475533/1b666518-662c-4f69-87a4-d4e5e98db075">
<img width="1618" alt="Screenshot 2024-06-18 at 12 11 41 PM" src="https://github.com/Acly/krita-ai-diffusion/assets/10475533/ce18882f-2b5c-4e27-84da-eed8440116cf">

**Comment by HendrikVH75** [comment]
Hey jmgpp!

I had the same issue on my M1 even after complete reinstall of krita and the ai-plugin. For some reason my server log spit out an error with the "comfyui-tooling-nodes" which is a ComfyUI custom node.

I went via terminal to the krita local server installation (which is in "/Users/USERNAME/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes"), removed the comfyui-tooling-nodes (rm -R) and did a clean git clone (git clone https://github.com/Acly/comfyui-tooling-nodes.git).

After restarting krita my images aren't black anymore. Maybe it helps ya, too.

Henry

**Comment by iamcavalon** [comment]
What if there are no "tooling node" errors, any idea what to do?

**Comment by iamcavalon** [comment]
What if there are no "tooling node" errors, any idea what to do?

**Comment by HendrikVH75** [comment]
Hey, I have no clue.
One day it worked after updating the local server nodes, day after I'm getting
black images again.

Strange thing is, you can log on the local server via browser because it's just
a ComfyUI installation. Prompting an image there works.
If you install a complete ComfyUI server and connect it to Krita, it works too.
Seems like there is a bug in the pipeline between Krita and the local server.

 
 

Gesendet: Mittwoch, 03. Juli 2024 um 21:17 Uhr
Von: "iamcavalon" ***@***.***>
An: "Acly/krita-ai-diffusion" ***@***.***>
Cc: "Hendrik van Heek" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [Acly/krita-ai-diffusion] Generated images are just black (Issue #783)


 

What if there are no "tooling node" errors, any idea what to do?

**Comment by Acly** [comment]
Can you try and [export a workflow](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#comfyui-workflow-export) which results in black image and run that in ComfyUI directly? I'd expect output to be black there too, but it might be some specific node/combination causing it.

**Comment by loloakira** [comment]
> Can you try and [export a workflow](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#comfyui-workflow-export) which results in black image and run that in ComfyUI directly? I'd expect output to be black there too, but it might be some specific node/combination causing it.

I have the exact same problem. I did what you asked for and it resulted in a black image too.

**Comment by aitormendez** [comment]
Same problem here. Macos 14.4.1 M2.

**Comment by EricChan1989** [comment]
change the sampler to "sd3-dpm++ 2m uniform" can perfectly fix this issue.
seems it just being a sampler issue

**Comment by aitormendez** [comment]
> change the sampler to "sd3-dpm++ 2m uniform" can perfectly fix this issue. seems it just being a sampler issue

Yes, that solves the problem. Thank you very much.

**Comment by parella007** [comment]
I am "kind" of having the same problem:
**black images** in files that a week ago were rendering fine.

MacOs 14.6.1

I cant figure out what made the difference because almost at the same time, i updated OS (to 14.6.1), I updated Krita (to 5.2.3), I updated the ai-diffusion plugin (to 1.22.0) and i installed the flux models (flux1-schnell-fp8.safetensors
flux1-dev-fp8.safetensors)

Everything seem to work OK and i was able to play with the Flux models for a week.
Today as i came back to a project i am working on using SDXL (juggernaut), every image came back black!, i read this thread and after some experimentation i found that changing the samplers does work, but only if i stay below 20 steps.

Lets say i use a XL model, with the default sampler (DPM++ 2M -Karras cfg:7 steps:20): i get a black image but if i change that to 19 steps, it works fine. (I did the same in the ComfyUI directly (http://127.0.0.1:8188/) : same thing: black images with anything above 20 steps). 

I thought this was a XL issue, but not, its exactly the same with 1.5 models. 19 steps fine, 20 steps black image. And this happens with any combination of samplers (euler ancestral -normal, DPM++ sde-gpu -Karras, etc...) black images if i jump from 19 to 20 steps.

Funny enough if i come back to flux, there i can jump to any number of steps (euler-simple) 60 steps!, snd it works fine.

**Comment by Acly** [comment]
This looks related: https://github.com/comfyanonymous/ComfyUI/pull/4548

If I read it correctly you can try providing `--force-upcast-attention` to ComfyUI

If you are using manage server install: [How to edit](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-pass-additional-arguments-to-comfyui)

**Comment by parella007** [comment]
> If I read it correctly you can try providing `--force-upcast-attention` to ComfyUI startup

Thanks a lot
That worked!
Ive been working like an hour with 1.5 and xl models and no more black images, with any number of steps.

**Comment by Plaghuurtne** [comment]
> If I read it correctly you can try providing `--force-upcast-attention` to ComfyUI startup

Works! Thank you

**Comment by Dunein** [comment]
Hey guys, 

I tried to expand a picture but outside the original border, it only prompts black. I've tried every solution in this topic but it didn't work.

Any ideas ?

**Comment by HendrikVH75** [comment]
Hey. For the next two weeks I'm on holiday. If the issue is still going on after my break I gonna export a workflow for you. --Gesendet mit der WEB.DE Mail AppAm 05.07.24, 10:08 schrieb Acly ***@***.***>:

   
  Can you try and export a workflow which results in black image and run that in ComfyUI directly? I'd expect output to be black there too, but it might be some specific node/combination causing it.
