### ISSUE TITLE
Weird canvas refresh/redraw issue with Undo when using Live Mode

### ISSUE THREAD

**Issue by freecoderwaifu** [Acly/krita-ai-diffusion#787]
When using Live mode and using Undo, the entire canvas doesn't redraw properly back to the previous undo points. Sometimes the squares that do refresh are smaller, sometimes they're larger, but the entire canvas doesn't refresh as it should. 

Zooming in and out doesn't cause it to refresh, but hiding and unhiding a layer does.

Video:

https://github.com/Acly/krita-ai-diffusion/assets/66507343/59d02dba-8622-4169-b1fb-4a4ddc7ff705

Generate and Refine work as expected. Undo also works as expected when not using the extension too. Only Live mode currently seems to have this issue.

Maybe related to how Live mode layers work now. 

I think having an option to go back to the old behavior, as mentioned in the update notes, is a good idea. Maybe a sort of toggle or even a separate button next to the current one, because honestly sometimes it's good to have each of the Live mode changes on their own layer, but sometimes it's also good to just update the current one without making a new layer, while working on the same picture.

**Comment by Acly** [comment]
Undo is tricky because Krita plugins don't have direct control over it. But I solved this in a different place by internally replacing the layer itself instead of modifying the content. It should work here too. The downside is that it will take 2 undo actions to revert. In a way it could be used as "feature" (apply will create a layer with the new content and remove the one with the old, hitting Undo once will bring back the layer with the old content so you end up with both).

As for options to solve this in a nicer way:
settings.json already supports two options `apply_behavior` and `apply_behavior_live`. The possible values are: `replace`, `layer`, `layer_hide_below`, `transparency_mask`

There's no UI for it yet, they were a last minute addition and I'm not sure yet which are the most useful. Also agree that this should be accessible via the apply button directly, but there are even more possibilities with regions, need to figure out which ones make the most sense.

**Comment by freecoderwaifu** [comment]
Thank you, set it to layer_hide_below and it works as before. 

Yeah I can see all these modes being useful in their own way, so I get trying to find the best one, 

Layers can be a way to "checkpoint" or mark major progress in an image, but sometimes there are smaller changes that aren't always worth a whole new layer, but still worth sending to canvas. 

Hiding the layer below after a new layer can be useful to quickly compare to a base sketch or a base image, if all new layers after it are hidden and only the current working one is visible. Transparency mask is also useful for regions and inpainting. 

I still think having a way to switch between this functionality on the main panel would be useful, in a way that also doesn't clutter it too much. I wouldn't mind the style selection dropdown being slightly shorter to make space for additional buttons, but that also depends on different screen resolutions and panel sizes and positions.

**Comment by Acly** [comment]
[1.18.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.18.1) adds one more button for Live. It behaves a bit differently with regions, which is probably not super intuitive, but it makes everything you might want to do reasonably accessible.

**Comment by freecoderwaifu** [comment]
Thank you, works perfectly, undo is fixed too.
