### ISSUE TITLE
Instalation corrupted after Krita crashed

### ISSUE THREAD

**Issue by ronaldomirandah** [Acly/krita-ai-diffusion#80]
After krita crashed, i got this screen, saying even Comfyui is not installed.

But all my models are still there, as Comfyui.

Any idea if there is some config. file i can delete?

Screenshot:

[ZtQEGx5.png (616×741) (imgur.com)](https://i.imgur.com/ZtQEGx5.png)

**Comment by Acly** [comment]
The installation is detected based by checking if corresponding files/folders exist, so there is no config file to restart it.

It sounds like ComfyUI is only partially there, but is skipped during installation because the folder exists. The installer can probably be improved in that regard.

If you want to avoid redownloading all the models, you can try fixing your ComfyUI manually by extracing contents of `.cache/ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2.zip` into your existing ComfyUI folder. Note that the zip has a folder inside, you need its contents.
