### ISSUE TITLE
Docker image aclysia/sd-comfyui-krita is not up to date

### ISSUE THREAD

**Issue by shahrin014** [Acly/krita-ai-diffusion#818]
I notice the docker image in https://hub.docker.com/r/aclysia/sd-comfyui-krita/tags is v1.16.1

The latest version is v1.18.1

I tried to automate this using github actions  but the free runner runs out of space.

Perhaps we can automate the docker build in a runner hosted on a cloud service?

**Comment by moiri-gamboni** [comment]
The permanently hosted solution you're talking about is Interstice? 
In any case, personally I would appreciate even a minimal image that's up to date, since I saw there were a lot of model changes in a recent update. 
But I'm wondering if it would not make more sense to have an image without the models altogether and have them downloaded in the post-start script?

**Comment by Acly** [comment]
> The permanently hosted solution you're talking about is Interstice?

Yes

I uploaded an up-to-date image now, tag is `v1.20.0` (next version) - but it should also work with v1.19.0. Only tested it local so far.

> But I'm wondering if it would not make more sense to have an image without the models altogether and have them downloaded in the post-start script?

That would be an improvement I think. It means there's few more things that can go wrong since it doesn't all come in one pre-built blob. But it would make building the image much easier and reduce duplication.

Adding a copy of this repo to the docker image and running download_models.py should work. Maybe it's possible to forward arguments to the script by editing the "Container start command" in the runpod template? That way people could pass for example `--no-sd15` and considerably decrease download size if they're not interested in SD1.5.

**Comment by Acly** [comment]
`aclysia/sd-comfyui-krita:v1.22.0` is the first "barebone" image which downloads models after start-up.

https://github.com/Acly/krita-ai-diffusion/wiki/Cloud-GPU#-customization
