### ISSUE TITLE
Is it possible to use inpaint models, is there any way to do it the way it used to be?

### ISSUE THREAD

**Issue by oleshanepro** [Acly/krita-ai-diffusion#837]
As I remember, early versions of the plugin had the option to use inpaint models. After Acly made inpaint support from LLLyasviel, you can no longer use inpaint versions. But the thing is, they handle the transition between layers much better and no seams are visible. This is clearly visible in any situation, no adjustments help, because only when using inpaint models is kept absolutely the same shade and color as the original image. Is there any possibility to return the option to select inpaint versions among the checkpoints list?

**Comment by Acly** [comment]
1. Inpaint models were never supported
2. The Fooocus inpaint model patch for SDXL actual comes from the same source as pre-merged inpaint models, it just does it on the fly instead of storing & loading another 6GB+ file on disk
3. I get great seamless results in many situations (I have a benchmark suite that compares inpaint methods) - but it's not always perfect, and color shift can happen. This is also the case for pre-merged inpaint model.

**Comment by oleshanepro** [comment]
> 1. Inpaint models were never supported
> 2. The Fooocus inpaint model patch for SDXL actual comes from the same source as pre-merged inpaint models, it just does it on the fly instead of storing & loading another 6GB+ file on disk
> 3. I get great seamless results in many situations (I have a benchmark suite that compares inpaint methods) - but it's not always perfect, and color shift can happen. This is also the case for pre-merged inpaint model.

Got it, thanks a lot for the great plugin. I must have gotten something mixed up.
