### ISSUE TITLE
Missing models even after downloading them with script

### ISSUE THREAD

**Issue by poornapragnarao** [Acly/krita-ai-diffusion#889]
Seeing this - 

`Error: Missing CLIP Vision model: sd1.5/pytorch_model.bin, sd1.5/model.safetensors, clip-vision_vit-h.safetensors, clip-vit-h-14-laion2b-s32b-b79k
Checking for files with a (partial) match:

See [Custom ComfyUI Setup](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup) for required models.
Check the client.log file for more details.`

My setup - 
1. Krita plugin version: Version 1.19.0
2. ComfyUI using sdwebui folders for models.
3. Downloaded required models from download_model.py (branch - tree/v1.19.0)
4. Copied the models downloaded to sdwebui models folders.

_Tried multiple restarts of comfy and krita and plugin. Same error._

Current folder structure - 

SD.WEBUI\WEBUI\MODELS
├───BLIP
│       model_base_caption_capfilt_large.pth
│
├───checkpoints
│       dreamshaperXL10_alpha2Xl10.safetensors
│       dreamshaper_8.safetensors
│       juggernautXL_version6Rundiffusion.safetensors
│       Put Stable Diffusion checkpoints here.txt
│       realisticVisionV51_v51VAE-inpainting.safetensors
│       realisticVisionV51_v51VAE.safetensors
│       zavychromaxl_v80.safetensors
│
├───clip_vision
│       clip-vision_vit-h.safetensors
│
├───Codeformer
│       codeformer-v0.1.0.pth
│
├───ControlNet
│       control-lora-canny-rank256.safetensors
│       control-lora-depth-rank128.safetensors
│       control-lora-depth-rank256.safetensors
│       control-lora-openposeXL2-rank256.safetensors
│       control-lora-recolor-rank256.safetensors
│       control-lora-sketch-rank256.safetensors
│       controlnetxlCNXL_xinsirOpenpose.safetensors
│       control_lora_rank128_v11f1e_sd15_tile_fp16.safetensors
│       control_lora_rank128_v11f1p_sd15_depth_fp16.safetensors
│       control_lora_rank128_v11p_sd15_normalbae_fp16.safetensors
│       control_lora_rank128_v11p_sd15_openpose_fp16.safetensors
│       control_lora_rank128_v11p_sd15_scribble_fp16.safetensors
│       control_lora_rank128_v11p_sd15_seg_fp16.safetensors
│       control_sd15_inpaint_depth_hand_fp16.safetensors
│       control_v11p_sd15_canny_fp16.safetensors
│       control_v11p_sd15_inpaint_fp16.safetensors
│       control_v11p_sd15_lineart_fp16.safetensors
│       control_v11p_sd15_softedge_fp16.safetensors
│       control_v1p_sd15_qrcode_monster.safetensors
│       mistoLine_rank256.safetensors
│       sai_xl_canny_256lora.safetensors
│       sai_xl_depth_256lora.safetensors
│       TTPLANET_Controlnet_Tile_realistic_v2_fp16.safetensors
│
├───deepbooru
│       Put your deepbooru release project folder here.txt
│
├───Embedding
│       bhands-neg.pt
│       JuggernautNegative-neg.pt
│
├───embeddings
│       EasyNegative.safetensors
│
├───ESRGAN
│       4x-UltraSharp.pth
│       4x_NMKD-Siax_200k.pth
│       ESRGAN_4x.pth
│
├───GFPGAN
├───hypernetworks
├───inpaint
│       fooocus_inpaint_head.pth
│       inpaint_v26.fooocus.patch
│       MAT_Places512_G_fp16.safetensors
│
├───ipadapter
│       ip-adapter-faceid-plusv2_sd15.bin
│       ip-adapter-faceid-plusv2_sdxl.bin
│       ip-adapter_sd15.safetensors
│       ip-adapter_sdxl_vit-h.safetensors
│
├───karlo
│       ViT-L-14_stats.th
│
├───LDSR
│       model.ckpt
│       project.yaml
│
├───Lora
│       Hyper-SD15-8steps-CFG-lora.safetensors
│       Hyper-SDXL-8steps-CFG-lora.safetensors
│       ip-adapter-faceid-plusv2_sd15_lora.safetensors
│       ip-adapter-faceid-plusv2_sdxl_lora.safetensors
│
├───loras
│       Hyper-SD15-8steps-CFG-lora.safetensors
│       Hyper-SDXL-8steps-CFG-lora.safetensors
│       ip-adapter-faceid-plusv2_sd15_lora.safetensors
│       ip-adapter-faceid-plusv2_sdxl_lora.safetensors
│
├───RealESRGAN
│       RealESRGAN_x4plus.pth
│
├───Stable-diffusion
│       dreamshaperXL10_alpha2Xl10.safetensors
│       dreamshaper_8.safetensors
│       juggernautXL_version6Rundiffusion.safetensors
│       Put Stable Diffusion checkpoints here.txt
│       realisticVisionV51_v51VAE-inpainting.safetensors
│       realisticVisionV51_v51VAE.safetensors
│       zavychromaxl_v80.safetensors
│
├───SwinIR
│       SwinIR_4x.pth
│
├───torch_deepdanbooru
│       model-resnet_custom_v3.pt
│
├───upscale_models
│       4x_NMKD-Superscale-SP_178000_G.pth
│       HAT_SRx4_ImageNet-pretrain.pth
│       OmniSR_X2_DIV2K.safetensors
│       OmniSR_X3_DIV2K.safetensors
│       OmniSR_X4_DIV2K.safetensors
│       Real_HAT_GAN_sharper.pth
│
├───VAE
│       Put VAE here.txt
│
└───VAE-approx
        model.pt
        vaeapprox-sdxl.pt

**Comment by Chepko932** [comment]
The download models script is not matching to the actual version, see the Changelog of the newest version

**Comment by Acly** [comment]
Folders look fine. Are you using extra_model_paths.yaml? Is the clip_vision folder mapped there?

**Comment by Chepko932** [comment]
Ive also got massive problems with the live generation since the update, tried everything

**Comment by aarongerber** [comment]
I think I'm setup properly and get this error:
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node DepthAnythingV2Preprocessor does not exist.', 'details': "Node ID '#2'", 'extra_info': {}}
FETCH DATA from: /home/.../ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json [DONE]
FETCH DATA from: /home/.../ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json [DONE]
FETCH DATA from: /home/.../ComfyUI/custom_nodes/ComfyUI-Manager/.cache/746607195_github-stats.json [DONE]
got prompt
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node DepthAnythingV2Preprocessor does not exist.', 'details': "Node ID '#2'", 'extra_info': {}}

**Comment by aarongerber** [comment]
Thanks, I’ll try that again. Thought I was updated.

**Comment by y98102** [comment]
put them into comfyUI/models/clip_version/SD1.5,even you have used extra_model_paths.yaml,put them into comfyUI models

**Comment by Saktawdi** [comment]
Hey, bro, how did you solve this problem? I'm facing the same issue.

**Comment by aarongerber** [comment]
I ended up doing an automatic install and merging its contents with my install. I think the instructions need to be updated. Or better yet, a script that just installs the files into an existing install.

**Comment by mdkberry** [comment]
after having to rebuild my comfyui Krita also had this problem.
the logs say it is connected but that the files are missing, though they are not missing. 

but if you look in Krita plugin config "connect" you can see what is needed. These need to be installed from the comfyui manager, not in Krita. it should then pick the models up again. here is what was missing from mine after a comfyui rebuild:

comfyui_controlnet_aux custom node - install it by searching for it in the comfyui manager

the below installs can use the github link in comfyui manager to install the links. just cut and paste (check your Krita settings config for the plugin and to confirm you need the same)

IP-Adapter - https://github.com/cubiq/ComfyUI_IPAdapter_plus
External Tooling Nodes - https://github.com/Acly/comfyui-tooling-nodes
Inpaint Nodes -  https://github.com/Acly/comfyui-inpaint-nodes

any other info was because the models had not been put in the correct folders under \models:
\inpaint
\ipadaptor
\controlnet

after sorting all that it worked.
