### ISSUE TITLE
how to debug this extension in vscode?

### ISSUE THREAD

**Issue by choigawoon** [Acly/krita-ai-diffusion#89]
This is my first time working in such an environment.
I would like to know how to debug using Visual Studio Code.

**Comment by Acly** [comment]
For some functionality there are tests, which are easy to debug. But all the UI only runs inside the Krita process because its API isn't available outside. I briefly tried to attach a debugger using "Attach using Process ID", but couldn't get it to work. I haven't needed it badly enough to invest more time so far.
If you figure it out I'd be interested though... (even though I suspect it will jump a lot into native code due to Qt and Krita).

**Comment by choigawoon** [comment]
Thank you for letting me know about your attempts, I will look into it more as well.

**Comment by Danamir** [comment]
I tried unsuccessfully with PyCharm too : the debugger can only attach to python processes so I'm unable to attach to the krita executable directly.
