### ISSUE TITLE
Xinsir strikes again, new ControlNet Tile for SDXL

### ISSUE THREAD

**Issue by Danamir** [Acly/krita-ai-diffusion#891]
Xinsir just released a new ControlNet tile for SDXL : https://huggingface.co/xinsir/controlnet-tile-sdxl-1.0

As for his other CNs, it is really good !

**Comment by Acly** [comment]
Better than the TTPlanet one?

There is a new depth model also. Although existing depth models were already quite decent.

I also want to try converting them into those nice 0.7G Lora formats instead of full 2.5G model...

**Comment by Acly** [comment]
I'm also getting good results, will add it to search paths at least.

I tried creating Control-Lora for Xinsir-Pose, Xinsir-Tile and [this Segmentation CN](https://huggingface.co/abovzv/sdxl_segmentation_controlnet_ade20k/tree/main). Only partial success though.
* Pose is too weak. Maybe because the full CN is already not that strong, and the Lora are generally a bit weaker.
* Tile kind of works but unfortunately takes on a habit of producing cloudy patterns and being more likely to shift color.
* The segmentation CN works well as Lora (it was a bit too strong at weight 1.0 anyway)

The tile behavior is weird, I wonder if the Xinsir models are trained on some finetune rather than base SDXL... couldn't find any info.

**Comment by pendave** [comment]
> search paths

Do you mean search paths for [krita-ai-diffusion](https://github.com/Acly/krita-ai-diffusion) or ComfyUI?

Any tutorial for search paths for [krita-ai-diffusion](https://github.com/Acly/krita-ai-diffusion) please?

**Comment by Acly** [comment]
Added. There is a new all-in-one unified control model: https://github.com/xinsir6/ControlNetPlus 
Quite interesting, similar idea as in #897
