### ISSUE TITLE
Error code 401 at Live mode

### ISSUE THREAD

**Issue by halitcan** [Acly/krita-ai-diffusion#90]
Hi ,
When i try to start live mode following error appears. V1.7.0 and 1.7.1 have  the same error. Log files attached.

![2023-11-21 05_10_17-Posta](https://github.com/Acly/krita-ai-diffusion/assets/7988534/54798f86-f672-4fa8-8594-c287e996e985)
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13421027/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/13421028/server.log)

**Comment by Acly** [comment]
The error on the server is `KeyError: 'ModelSamplingDiscrete'`. For some reason it cannot find the "ModelSamplingDiscrete" node. It should be in a file `nodes_model_advanced.py` in `...\.server\ComfyUI\comfy_extras`.
Usually if it's missing it means ComfyUI version is too old, but since you used the plugin installer it should be the correct version.

I don't have an explanation, just some things to check
* is the file there?
* if you open Comfy web UI (go to `127.0.0.1:8188` in your browser while Krita is running) check if the node is there: right click > add node > advanced > model > ModelSamplingDiscrete

**Comment by Blake1223** [comment]
> 服务器上的错误是`KeyError: 'ModelSamplingDiscrete'`。由于某种原因，它找不到“ModelSamplingDiscrete”节点。它应该`nodes_model_advanced.py`位于`...\.server\ComfyUI\comfy_extras`. 通常，如果它丢失，则意味着 ComfyUI 版本太旧，但由于您使用了插件安装程序，因此它应该是正确的版本。
> 
> 我没有解释，只是需要检查一些事情
> 
> * 文件在那里吗？
> * `127.0.0.1:8188`如果您打开 Comfy Web UI（在 Krita 运行时在浏览器中转至），请检查该节点是否存在：右键单击 > 添加节点 > 高级 > 模型 > ModelSamplingDiscrete



> The error on the server is `KeyError: 'ModelSamplingDiscrete'`. For some reason it cannot find the "ModelSamplingDiscrete" node. It should be in a file `nodes_model_advanced.py` in `...\.server\ComfyUI\comfy_extras`. Usually if it's missing it means ComfyUI version is too old, but since you used the plugin installer it should be the correct version.
> 
> I don't have an explanation, just some things to check
> 
> * is the file there?
> * if you open Comfy web UI (go to `127.0.0.1:8188` in your browser while Krita is running) check if the node is there: right click > add node > advanced > model > ModelSamplingDiscrete

  NO  found  ModelSamplingDiscrete

**Comment by Blake1223** [comment]
NO  found ModelSamplingDiscrete

**Comment by halitcan** [comment]
Thank you. I just deleted the ComfyUI folder and reinstalled it. It worked.
