### ISSUE TITLE
[Improvement] Could you please "Undo" and "Redo" specially for this plugin?

### ISSUE THREAD

**Issue by pendave** [Acly/krita-ai-diffusion#924]
![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/1a56ee50-0636-4cfa-bf4a-976d5590643a)

I'd like to undo to redo just like Ctrl+Z & Ctrl+Shift+Z as in the original Krita/Photoshop etc. but especially for controling the behaves actions done in [krita-ai-diffusion](https://github.com/Acly/krita-ai-diffusion) interface.

For instance, I adjust a strength, scroller bar, add a control layer, delete a control layer........ I could recover to the former state if I press
![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/a459de66-aa7c-4273-b85e-7cab42161c40)
And if I prefer to go forward I can go back to press
![image](https://github.com/Acly/krita-ai-diffusion/assets/1331881/861267ef-849a-48c6-b800-c6fee706677c)

This need is reasonable I think.

**Comment by GeminiSquishGames** [comment]
That could be handy, but having it be in the Krita history system seems better. If you could use the existing History, it would probably be easier and more functional to use what is already there, thus everything is procedural and you ctrl+z. Otherwise having some quick buttons to save/load different settings would be more optimal, IMHO. Also, when undoing things in Krita, the regions to old layers that come back on undo are unlinked, might be nice for them to remember their linked regions? If you have a good amount of layers linked to regional prompts, it can be a pain to relink them by hand. At least it remembers the prompts and gives a quick button to relink.

**Comment by Acly** [comment]
Plugins don't have direct control over Krita's undo/redo. It just works for built-in actions.

I don't like the idea of adding an extra undo/redo history on top. It sounds confusing and would have a relatively high cost.
