### ISSUE TITLE
How does animation work? 

### ISSUE THREAD

**Issue by GeminiSquishGames** [Acly/krita-ai-diffusion#958]
Is there a help for this? I noticed the wiki is a bit low on infos and I didn't see anything in the setup at the head of the repo. I know I risk looking dumb as usual but I cannot find it. 

Can't seem to get it to work as I think it's intended to. All I can do is turn on live, draw a frame, generate apply to new layer, and merge down to the animation layer, repeat. I can't apply to active layer or it erases all the frames with the one image of the generated result even if I have a blank frame for it. The red record button doesn't do anything for me but turn on live mode. If I turn it off, it turns off live and creates a layer and does nothing more that helps me than doing like I mentioned before, but it's kinda worse as I have to turn live on again. 

Generate in the animation mode below live, acts like it's generating each frame from the animation layer, but it doesn't always put them anywhere, in fact, it rarely seems to and I don't know what I'm doing differently to make it work when it happens. Single frame by frame tends to work more often but also seems unreliable much of the time. And it keeps making hundreds of hold frames, for whatever reason.

Also, the onion skin has to be turned off or it will use that for generation. It's a bit of a pain in the neck, but I assume it will always be using the internal viewport of the canvas being drawn on and there isn't a way around that. So you turn it off before selecting the generation, then turn it back on and go to your next frame and/or layer and/or solid surface by which to wack your noggin on.

**Comment by polytect** [comment]
Hi, yes, i had the same question, this is valid question, but not much information about it.
It actually doesn't generate the animation by itself, I too thought it does. It is confusing at first.

**How you might think it works:**
You imput a prompt and you get an animation.
**This is false.**

**How it actually works:**
You need to have an existing animation in order to process it via AI.
For example try to import any animated GIF image as animation layer, and then use the AI animation tool with 20% strength, this will proccess each frame individually.

If you want to create your own animation, like lightning, you will need first to draw it frame by frame first and the process it with AI. Or use Transfoms (zooming, spining, ect) export to animation layer.


I think for generating live animations just from prompt, we would need different models. 

It is not perfect, but interesting way to work.

In order to make smooth animation without artifacts, you will need to work frame by frame while keeping the same SEED.


https://github.com/user-attachments/assets/c32c7b7f-ea90-4c7e-bdfe-aae114f651e6

**Comment by GeminiSquishGames** [comment]
Sorry if I didn't explain well, but it seems there was a misunderstanding. I know this isn't a magic animation maker, and I'm using it as instructed. However, it's frustrating and not working as expected.

I've tried using both my own hand-made frames and frames from movie files. The problem is that the generation appears to be happening in the script's docker, but the generated frames aren't being placed anywhere—not in a new layer or even the existing animation layer. This issue arises when using the fourth option under Live mode, which is supposed to img2img an entire animation. Single frame mode almost works but surprisingly, doing animation directly in ComfyUI with the simple image edit node and the image accumulator node works better, though it feels like it shouldn't, and something seems wrong. This should be easier and mostly help me generate, place into animation, and work on next frame much easier. I think it would if it was actually placing the generated frames in the proper frame in a new animation layer, but it doesn't do anything after it generates things. I have to manually generate in Live (or even just not live refine mode) and do something with the new layer after I Apply to New Layer. Again, I can't just apply to active layer, it destroys any frames already present.

The only thing that works somewhat consistently is Live mode, and only when I don't use the red button. When I draw a frame by hand and want to add the generated content from the docker to the animation, I have to use Apply as Layer (not Apply to Active, as it destroys all my frames). Then, I need to carefully merge that frame into the animation layer, often pushing the frame down manually because merging layers doesn't work well. I frequently have to undo to recover my existing frames, as merging deletes them. This process is far from ideal and doesn't allow me to move smoothly to the next frame after generation. I should be able to generate frames and let it handle them, but I get nothing back even though it looks like it's working.

Additionally, I feel like I should be able to use a set of depth or open pose frames with ControlNet, but it only uses one frame and doesn't automatically generate depth animation from my starting frames.

**Comment by polytect** [comment]
Ok this is more sophisticated bug.
I didn't have this, but i will try to play around and monitor how it behaves.
Usually, the original animation layer should be untouched, new layer created [generated] and thats it.
Need to play with duplicated source animation layers also. The same bug might be present on normal single frame generations.

**Comment by Acly** [comment]
Animation support is pretty rudimentary.
The workspace does image batch processing: #434
The red record button in Live mode is more of a [gimmick](https://www.youtube.com/watch?v=PDDJ1k-0hmU), I'm not sure I will keep it.

It's unclear if/when there will be more, because most of Krita's animation features are not exposed for plugins. The generated frames are currently added with File > Import animation frames...
Note that if it doesn't work for some reason you can also find the frames where you saved your document and import them yourself. The renaming issue sounds like some kind of timing thing, where the renaming happens before the new animation layer is added. Not always clear when Krita operations are actually finished.

**Comment by Marksusu** [comment]
目前的 Krita 没有类似剪辑软件里的“素材库、时间轴、视频/音频轨道”之类的概念，所以，只能长期停留在“逐帧动画”的阶段。仅有的音频处理也只能听见，无法看见，没有波形预览，也不能处理多个轨道。

目前 Krita 对帧的操作也十分有限，没法在一个列表里预览多个帧的连续变化，只能在图层面板里查看选中的某一帧。甚至有时你对图层的一次操作（比如合并）会影响（破坏）该图层里所有帧的内容。

如果能参考很久以前的一个利用连续图层制做动画的插件思路，我们可以用“图层组”来组织用于视频剪辑的素材，更多涉及运动、特效、音频和多轨道的操作，都交给剪辑软件完成。

一个图层组，可以只包含一个图层，是一个仅需在剪辑软件里缩放、平移、转动的图像素材，插在哪个时间点，放在哪个轨道，都在视频剪辑软件里操作。

一个图层组，也可以包含多个图层，是一个连续动作的多个帧（关键帧、连续帧，都可以，但都以图层的形式来表达，便于人类编辑，也便于剪辑软件识别），至于每一帧的持续时长，要给 Krita 和剪辑软件等同的接收和操作能力，便于反复修改。

如上思路，是以“目前 Krita 没有获得音、视频剪辑能力”为前提的，需要与 ShotCut 这类剪辑软件配合，也需要反复尝试去验证是否可行。

**Comment by GeminiSquishGames** [comment]
> The red record button in Live mode is more of a [gimmick](https://www.youtube.com/watch?v=PDDJ1k-0hmU), I'm not sure I will keep it.

I think my card is to sluggish to do it right, so that could be my issue with a lot of things. The timing very well could just be crap since it takes a while for frames to render. I thought that Krita recorded strokes as keyframes but I'm probably thinking of Corel Painter. But if it does, I guess it would be the same as just generating from that stroke by stroke animation, just not live. It would be nice but I can barely make decent use of live mode for just drawing as it is with the 6GB RTX2060. I have to eat more than I need fast AI image gen I suppose. I think for animation I may have to stick to Blender's grease pencil and there are some good SD implementations but one has to wait for the blender rendering as well as the SD rendering so it takes longer, but one can apply a pose, depth, and other control net passes after the render and before the SD generation, as well as change the prompt at specific key frames in a list, but Blender is a boss with python accessible features, Krita seems to lack a lot as Marksusu, I think, mentions. I've never tickled cats but the chickens tend to dust themselves. They think outside the box... er coop.

**Comment by Acly** [comment]
It's "live", records frames at the speed your GPU produces them. So you just have to draw veeery slowly!

Using Krita canvas recording and running that through batch diffusion afterwards probably makes more sense.
