### ISSUE TITLE
krita ai not using my gpu ( 7700xt ) 

### ISSUE THREAD

**Issue by wavy43** [Acly/krita-ai-diffusion#994]
it always stops my ai generation and says i dont have enough memory (the card they gave me has 1 vram) https://imgur.com/a/ZbeIeWX

**Comment by polytect** [comment]
Please provide, the OS you are using, the GPU you are using, version. Type of computer.
What was tried.

Does your laptop have Dual Graphics?

**Comment by LeF0URBE** [comment]
i assume you're on windows.
AMD+Windows is a loosing combo and you will have a REALLY FUN time.
You will have to make your own local custom ComfyUI installation that you can link to the krita extention.
since ComfyUI (the backend to run krita ai) can only run AMD with Linux... you will likely have to setup a VM or something to run a Linux instance on your PC and use the custom managed server (in remote mode) to link your VM Linux to your Krita windows instance.

**Comment by Acly** [comment]
You can install with DirectML to run on AMD/Windows. It just doesn't work very well.

The card is always reported with 1 GB VRAM even if it has more. It needs 12GB or more to run even on fairly low resolution images.

I'm considering just dropping this option though, it's lagging really far behind and there doesn't seem to be any motivation (by AMD, Microsoft, etc) to do anything about it.

Can also try ZLUDA or rocM via WSL, but have to set it up yourself.
